// Code generated by ent, DO NOT EDIT.

package ccgocommandaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ccgocommandaudit type in the database.
	Label = "ccgo_command_audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldWorkspaceID holds the string denoting the workspace_id field in the database.
	FieldWorkspaceID = "workspace_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldCommandHash holds the string denoting the command_hash field in the database.
	FieldCommandHash = "command_hash"
	// FieldRedactedCommand holds the string denoting the redacted_command field in the database.
	FieldRedactedCommand = "redacted_command"
	// FieldServerCwd holds the string denoting the server_cwd field in the database.
	FieldServerCwd = "server_cwd"
	// FieldLocalCwd holds the string denoting the local_cwd field in the database.
	FieldLocalCwd = "local_cwd"
	// FieldExitCode holds the string denoting the exit_code field in the database.
	FieldExitCode = "exit_code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// Table holds the table name of the ccgocommandaudit in the database.
	Table = "ccgo_command_audits"
)

// Columns holds all SQL columns for ccgocommandaudit fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldWorkspaceID,
	FieldUserID,
	FieldRunID,
	FieldRequestID,
	FieldCommandHash,
	FieldRedactedCommand,
	FieldServerCwd,
	FieldLocalCwd,
	FieldExitCode,
	FieldStatus,
	FieldFailureReason,
	FieldStartedAt,
	FieldFinishedAt,
	FieldDurationMs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// CommandHashValidator is a validator for the "command_hash" field. It is called by the builders before save.
	CommandHashValidator func(string) error
	// DefaultRedactedCommand holds the default value on creation for the "redacted_command" field.
	DefaultRedactedCommand string
	// ServerCwdValidator is a validator for the "server_cwd" field. It is called by the builders before save.
	ServerCwdValidator func(string) error
	// LocalCwdValidator is a validator for the "local_cwd" field. It is called by the builders before save.
	LocalCwdValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFailureReason holds the default value on creation for the "failure_reason" field.
	DefaultFailureReason string
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int64
)

// OrderOption defines the ordering options for the CcgoCommandAudit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWorkspaceID orders the results by the workspace_id field.
func ByWorkspaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByCommandHash orders the results by the command_hash field.
func ByCommandHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommandHash, opts...).ToFunc()
}

// ByRedactedCommand orders the results by the redacted_command field.
func ByRedactedCommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedactedCommand, opts...).ToFunc()
}

// ByServerCwd orders the results by the server_cwd field.
func ByServerCwd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerCwd, opts...).ToFunc()
}

// ByLocalCwd orders the results by the local_cwd field.
func ByLocalCwd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalCwd, opts...).ToFunc()
}

// ByExitCode orders the results by the exit_code field.
func ByExitCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExitCode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}
