// Code generated by ent, DO NOT EDIT.

package ccgocommandaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldWorkspaceID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldUserID, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldRunID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldRequestID, v))
}

// CommandHash applies equality check predicate on the "command_hash" field. It's identical to CommandHashEQ.
func CommandHash(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldCommandHash, v))
}

// RedactedCommand applies equality check predicate on the "redacted_command" field. It's identical to RedactedCommandEQ.
func RedactedCommand(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldRedactedCommand, v))
}

// ServerCwd applies equality check predicate on the "server_cwd" field. It's identical to ServerCwdEQ.
func ServerCwd(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldServerCwd, v))
}

// LocalCwd applies equality check predicate on the "local_cwd" field. It's identical to LocalCwdEQ.
func LocalCwd(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldLocalCwd, v))
}

// ExitCode applies equality check predicate on the "exit_code" field. It's identical to ExitCodeEQ.
func ExitCode(v int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldExitCode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldStatus, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldFailureReason, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldFinishedAt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldDurationMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldUpdatedAt, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldWorkspaceID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldUserID, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldRunID, v))
}

// RunIDIsNil applies the IsNil predicate on the "run_id" field.
func RunIDIsNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIsNull(FieldRunID))
}

// RunIDNotNil applies the NotNil predicate on the "run_id" field.
func RunIDNotNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotNull(FieldRunID))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContainsFold(FieldRequestID, v))
}

// CommandHashEQ applies the EQ predicate on the "command_hash" field.
func CommandHashEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldCommandHash, v))
}

// CommandHashNEQ applies the NEQ predicate on the "command_hash" field.
func CommandHashNEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldCommandHash, v))
}

// CommandHashIn applies the In predicate on the "command_hash" field.
func CommandHashIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldCommandHash, vs...))
}

// CommandHashNotIn applies the NotIn predicate on the "command_hash" field.
func CommandHashNotIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldCommandHash, vs...))
}

// CommandHashGT applies the GT predicate on the "command_hash" field.
func CommandHashGT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldCommandHash, v))
}

// CommandHashGTE applies the GTE predicate on the "command_hash" field.
func CommandHashGTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldCommandHash, v))
}

// CommandHashLT applies the LT predicate on the "command_hash" field.
func CommandHashLT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldCommandHash, v))
}

// CommandHashLTE applies the LTE predicate on the "command_hash" field.
func CommandHashLTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldCommandHash, v))
}

// CommandHashContains applies the Contains predicate on the "command_hash" field.
func CommandHashContains(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContains(FieldCommandHash, v))
}

// CommandHashHasPrefix applies the HasPrefix predicate on the "command_hash" field.
func CommandHashHasPrefix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasPrefix(FieldCommandHash, v))
}

// CommandHashHasSuffix applies the HasSuffix predicate on the "command_hash" field.
func CommandHashHasSuffix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasSuffix(FieldCommandHash, v))
}

// CommandHashEqualFold applies the EqualFold predicate on the "command_hash" field.
func CommandHashEqualFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEqualFold(FieldCommandHash, v))
}

// CommandHashContainsFold applies the ContainsFold predicate on the "command_hash" field.
func CommandHashContainsFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContainsFold(FieldCommandHash, v))
}

// RedactedCommandEQ applies the EQ predicate on the "redacted_command" field.
func RedactedCommandEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldRedactedCommand, v))
}

// RedactedCommandNEQ applies the NEQ predicate on the "redacted_command" field.
func RedactedCommandNEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldRedactedCommand, v))
}

// RedactedCommandIn applies the In predicate on the "redacted_command" field.
func RedactedCommandIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldRedactedCommand, vs...))
}

// RedactedCommandNotIn applies the NotIn predicate on the "redacted_command" field.
func RedactedCommandNotIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldRedactedCommand, vs...))
}

// RedactedCommandGT applies the GT predicate on the "redacted_command" field.
func RedactedCommandGT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldRedactedCommand, v))
}

// RedactedCommandGTE applies the GTE predicate on the "redacted_command" field.
func RedactedCommandGTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldRedactedCommand, v))
}

// RedactedCommandLT applies the LT predicate on the "redacted_command" field.
func RedactedCommandLT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldRedactedCommand, v))
}

// RedactedCommandLTE applies the LTE predicate on the "redacted_command" field.
func RedactedCommandLTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldRedactedCommand, v))
}

// RedactedCommandContains applies the Contains predicate on the "redacted_command" field.
func RedactedCommandContains(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContains(FieldRedactedCommand, v))
}

// RedactedCommandHasPrefix applies the HasPrefix predicate on the "redacted_command" field.
func RedactedCommandHasPrefix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasPrefix(FieldRedactedCommand, v))
}

// RedactedCommandHasSuffix applies the HasSuffix predicate on the "redacted_command" field.
func RedactedCommandHasSuffix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasSuffix(FieldRedactedCommand, v))
}

// RedactedCommandEqualFold applies the EqualFold predicate on the "redacted_command" field.
func RedactedCommandEqualFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEqualFold(FieldRedactedCommand, v))
}

// RedactedCommandContainsFold applies the ContainsFold predicate on the "redacted_command" field.
func RedactedCommandContainsFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContainsFold(FieldRedactedCommand, v))
}

// ServerCwdEQ applies the EQ predicate on the "server_cwd" field.
func ServerCwdEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldServerCwd, v))
}

// ServerCwdNEQ applies the NEQ predicate on the "server_cwd" field.
func ServerCwdNEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldServerCwd, v))
}

// ServerCwdIn applies the In predicate on the "server_cwd" field.
func ServerCwdIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldServerCwd, vs...))
}

// ServerCwdNotIn applies the NotIn predicate on the "server_cwd" field.
func ServerCwdNotIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldServerCwd, vs...))
}

// ServerCwdGT applies the GT predicate on the "server_cwd" field.
func ServerCwdGT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldServerCwd, v))
}

// ServerCwdGTE applies the GTE predicate on the "server_cwd" field.
func ServerCwdGTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldServerCwd, v))
}

// ServerCwdLT applies the LT predicate on the "server_cwd" field.
func ServerCwdLT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldServerCwd, v))
}

// ServerCwdLTE applies the LTE predicate on the "server_cwd" field.
func ServerCwdLTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldServerCwd, v))
}

// ServerCwdContains applies the Contains predicate on the "server_cwd" field.
func ServerCwdContains(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContains(FieldServerCwd, v))
}

// ServerCwdHasPrefix applies the HasPrefix predicate on the "server_cwd" field.
func ServerCwdHasPrefix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasPrefix(FieldServerCwd, v))
}

// ServerCwdHasSuffix applies the HasSuffix predicate on the "server_cwd" field.
func ServerCwdHasSuffix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasSuffix(FieldServerCwd, v))
}

// ServerCwdEqualFold applies the EqualFold predicate on the "server_cwd" field.
func ServerCwdEqualFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEqualFold(FieldServerCwd, v))
}

// ServerCwdContainsFold applies the ContainsFold predicate on the "server_cwd" field.
func ServerCwdContainsFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContainsFold(FieldServerCwd, v))
}

// LocalCwdEQ applies the EQ predicate on the "local_cwd" field.
func LocalCwdEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldLocalCwd, v))
}

// LocalCwdNEQ applies the NEQ predicate on the "local_cwd" field.
func LocalCwdNEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldLocalCwd, v))
}

// LocalCwdIn applies the In predicate on the "local_cwd" field.
func LocalCwdIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldLocalCwd, vs...))
}

// LocalCwdNotIn applies the NotIn predicate on the "local_cwd" field.
func LocalCwdNotIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldLocalCwd, vs...))
}

// LocalCwdGT applies the GT predicate on the "local_cwd" field.
func LocalCwdGT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldLocalCwd, v))
}

// LocalCwdGTE applies the GTE predicate on the "local_cwd" field.
func LocalCwdGTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldLocalCwd, v))
}

// LocalCwdLT applies the LT predicate on the "local_cwd" field.
func LocalCwdLT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldLocalCwd, v))
}

// LocalCwdLTE applies the LTE predicate on the "local_cwd" field.
func LocalCwdLTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldLocalCwd, v))
}

// LocalCwdContains applies the Contains predicate on the "local_cwd" field.
func LocalCwdContains(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContains(FieldLocalCwd, v))
}

// LocalCwdHasPrefix applies the HasPrefix predicate on the "local_cwd" field.
func LocalCwdHasPrefix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasPrefix(FieldLocalCwd, v))
}

// LocalCwdHasSuffix applies the HasSuffix predicate on the "local_cwd" field.
func LocalCwdHasSuffix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasSuffix(FieldLocalCwd, v))
}

// LocalCwdEqualFold applies the EqualFold predicate on the "local_cwd" field.
func LocalCwdEqualFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEqualFold(FieldLocalCwd, v))
}

// LocalCwdContainsFold applies the ContainsFold predicate on the "local_cwd" field.
func LocalCwdContainsFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContainsFold(FieldLocalCwd, v))
}

// ExitCodeEQ applies the EQ predicate on the "exit_code" field.
func ExitCodeEQ(v int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldExitCode, v))
}

// ExitCodeNEQ applies the NEQ predicate on the "exit_code" field.
func ExitCodeNEQ(v int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldExitCode, v))
}

// ExitCodeIn applies the In predicate on the "exit_code" field.
func ExitCodeIn(vs ...int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldExitCode, vs...))
}

// ExitCodeNotIn applies the NotIn predicate on the "exit_code" field.
func ExitCodeNotIn(vs ...int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldExitCode, vs...))
}

// ExitCodeGT applies the GT predicate on the "exit_code" field.
func ExitCodeGT(v int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldExitCode, v))
}

// ExitCodeGTE applies the GTE predicate on the "exit_code" field.
func ExitCodeGTE(v int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldExitCode, v))
}

// ExitCodeLT applies the LT predicate on the "exit_code" field.
func ExitCodeLT(v int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldExitCode, v))
}

// ExitCodeLTE applies the LTE predicate on the "exit_code" field.
func ExitCodeLTE(v int) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldExitCode, v))
}

// ExitCodeIsNil applies the IsNil predicate on the "exit_code" field.
func ExitCodeIsNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIsNull(FieldExitCode))
}

// ExitCodeNotNil applies the NotNil predicate on the "exit_code" field.
func ExitCodeNotNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotNull(FieldExitCode))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContainsFold(FieldStatus, v))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldContainsFold(FieldFailureReason, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotNull(FieldFinishedAt))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.FieldLTE(FieldDurationMs, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CcgoCommandAudit) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CcgoCommandAudit) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CcgoCommandAudit) predicate.CcgoCommandAudit {
	return predicate.CcgoCommandAudit(sql.NotPredicates(p))
}
