// Code generated by ent, DO NOT EDIT.

package ccgoworkspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ccgoworkspace type in the database.
	Label = "ccgo_workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldWorkspaceSlug holds the string denoting the workspace_slug field in the database.
	FieldWorkspaceSlug = "workspace_slug"
	// FieldServerRoot holds the string denoting the server_root field in the database.
	FieldServerRoot = "server_root"
	// FieldLocalRootHash holds the string denoting the local_root_hash field in the database.
	FieldLocalRootHash = "local_root_hash"
	// FieldLocalRootDisplay holds the string denoting the local_root_display field in the database.
	FieldLocalRootDisplay = "local_root_display"
	// FieldLocalRootRedacted holds the string denoting the local_root_redacted field in the database.
	FieldLocalRootRedacted = "local_root_redacted"
	// FieldOs holds the string denoting the os field in the database.
	FieldOs = "os"
	// FieldPathStyle holds the string denoting the path_style field in the database.
	FieldPathStyle = "path_style"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// Table holds the table name of the ccgoworkspace in the database.
	Table = "ccgo_workspaces"
)

// Columns holds all SQL columns for ccgoworkspace fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldWorkspaceSlug,
	FieldServerRoot,
	FieldLocalRootHash,
	FieldLocalRootDisplay,
	FieldLocalRootRedacted,
	FieldOs,
	FieldPathStyle,
	FieldDeviceID,
	FieldStatus,
	FieldLastSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// WorkspaceSlugValidator is a validator for the "workspace_slug" field. It is called by the builders before save.
	WorkspaceSlugValidator func(string) error
	// ServerRootValidator is a validator for the "server_root" field. It is called by the builders before save.
	ServerRootValidator func(string) error
	// LocalRootHashValidator is a validator for the "local_root_hash" field. It is called by the builders before save.
	LocalRootHashValidator func(string) error
	// LocalRootDisplayValidator is a validator for the "local_root_display" field. It is called by the builders before save.
	LocalRootDisplayValidator func(string) error
	// DefaultLocalRootRedacted holds the default value on creation for the "local_root_redacted" field.
	DefaultLocalRootRedacted string
	// OsValidator is a validator for the "os" field. It is called by the builders before save.
	OsValidator func(string) error
	// PathStyleValidator is a validator for the "path_style" field. It is called by the builders before save.
	PathStyleValidator func(string) error
	// DefaultDeviceID holds the default value on creation for the "device_id" field.
	DefaultDeviceID string
	// DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	DeviceIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the CcgoWorkspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByWorkspaceSlug orders the results by the workspace_slug field.
func ByWorkspaceSlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceSlug, opts...).ToFunc()
}

// ByServerRoot orders the results by the server_root field.
func ByServerRoot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerRoot, opts...).ToFunc()
}

// ByLocalRootHash orders the results by the local_root_hash field.
func ByLocalRootHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalRootHash, opts...).ToFunc()
}

// ByLocalRootDisplay orders the results by the local_root_display field.
func ByLocalRootDisplay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalRootDisplay, opts...).ToFunc()
}

// ByLocalRootRedacted orders the results by the local_root_redacted field.
func ByLocalRootRedacted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalRootRedacted, opts...).ToFunc()
}

// ByOs orders the results by the os field.
func ByOs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOs, opts...).ToFunc()
}

// ByPathStyle orders the results by the path_style field.
func ByPathStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPathStyle, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}
