// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ccgoworkspace"
)

// CcgoWorkspace is the model entity for the CcgoWorkspace schema.
type CcgoWorkspace struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// WorkspaceSlug holds the value of the "workspace_slug" field.
	WorkspaceSlug string `json:"workspace_slug,omitempty"`
	// ServerRoot holds the value of the "server_root" field.
	ServerRoot string `json:"server_root,omitempty"`
	// LocalRootHash holds the value of the "local_root_hash" field.
	LocalRootHash string `json:"local_root_hash,omitempty"`
	// LocalRootDisplay holds the value of the "local_root_display" field.
	LocalRootDisplay string `json:"local_root_display,omitempty"`
	// LocalRootRedacted holds the value of the "local_root_redacted" field.
	LocalRootRedacted string `json:"local_root_redacted,omitempty"`
	// Os holds the value of the "os" field.
	Os string `json:"os,omitempty"`
	// PathStyle holds the value of the "path_style" field.
	PathStyle string `json:"path_style,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID string `json:"device_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt   *time.Time `json:"last_seen_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CcgoWorkspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ccgoworkspace.FieldID, ccgoworkspace.FieldUserID:
			values[i] = new(sql.NullInt64)
		case ccgoworkspace.FieldWorkspaceSlug, ccgoworkspace.FieldServerRoot, ccgoworkspace.FieldLocalRootHash, ccgoworkspace.FieldLocalRootDisplay, ccgoworkspace.FieldLocalRootRedacted, ccgoworkspace.FieldOs, ccgoworkspace.FieldPathStyle, ccgoworkspace.FieldDeviceID, ccgoworkspace.FieldStatus:
			values[i] = new(sql.NullString)
		case ccgoworkspace.FieldCreatedAt, ccgoworkspace.FieldUpdatedAt, ccgoworkspace.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CcgoWorkspace fields.
func (_m *CcgoWorkspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ccgoworkspace.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ccgoworkspace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ccgoworkspace.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ccgoworkspace.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case ccgoworkspace.FieldWorkspaceSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_slug", values[i])
			} else if value.Valid {
				_m.WorkspaceSlug = value.String
			}
		case ccgoworkspace.FieldServerRoot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_root", values[i])
			} else if value.Valid {
				_m.ServerRoot = value.String
			}
		case ccgoworkspace.FieldLocalRootHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_root_hash", values[i])
			} else if value.Valid {
				_m.LocalRootHash = value.String
			}
		case ccgoworkspace.FieldLocalRootDisplay:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_root_display", values[i])
			} else if value.Valid {
				_m.LocalRootDisplay = value.String
			}
		case ccgoworkspace.FieldLocalRootRedacted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_root_redacted", values[i])
			} else if value.Valid {
				_m.LocalRootRedacted = value.String
			}
		case ccgoworkspace.FieldOs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os", values[i])
			} else if value.Valid {
				_m.Os = value.String
			}
		case ccgoworkspace.FieldPathStyle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path_style", values[i])
			} else if value.Valid {
				_m.PathStyle = value.String
			}
		case ccgoworkspace.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case ccgoworkspace.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ccgoworkspace.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = new(time.Time)
				*_m.LastSeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CcgoWorkspace.
// This includes values selected through modifiers, order, etc.
func (_m *CcgoWorkspace) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CcgoWorkspace.
// Note that you need to call CcgoWorkspace.Unwrap() before calling this method if this CcgoWorkspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CcgoWorkspace) Update() *CcgoWorkspaceUpdateOne {
	return NewCcgoWorkspaceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CcgoWorkspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CcgoWorkspace) Unwrap() *CcgoWorkspace {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CcgoWorkspace is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CcgoWorkspace) String() string {
	var builder strings.Builder
	builder.WriteString("CcgoWorkspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("workspace_slug=")
	builder.WriteString(_m.WorkspaceSlug)
	builder.WriteString(", ")
	builder.WriteString("server_root=")
	builder.WriteString(_m.ServerRoot)
	builder.WriteString(", ")
	builder.WriteString("local_root_hash=")
	builder.WriteString(_m.LocalRootHash)
	builder.WriteString(", ")
	builder.WriteString("local_root_display=")
	builder.WriteString(_m.LocalRootDisplay)
	builder.WriteString(", ")
	builder.WriteString("local_root_redacted=")
	builder.WriteString(_m.LocalRootRedacted)
	builder.WriteString(", ")
	builder.WriteString("os=")
	builder.WriteString(_m.Os)
	builder.WriteString(", ")
	builder.WriteString("path_style=")
	builder.WriteString(_m.PathStyle)
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastSeenAt; v != nil {
		builder.WriteString("last_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CcgoWorkspaces is a parsable slice of CcgoWorkspace.
type CcgoWorkspaces []*CcgoWorkspace
