// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ccgodevicelogin"
)

// CcgoDeviceLoginCreate is the builder for creating a CcgoDeviceLogin entity.
type CcgoDeviceLoginCreate struct {
	config
	mutation *CcgoDeviceLoginMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CcgoDeviceLoginCreate) SetCreatedAt(v time.Time) *CcgoDeviceLoginCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CcgoDeviceLoginCreate) SetNillableCreatedAt(v *time.Time) *CcgoDeviceLoginCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CcgoDeviceLoginCreate) SetUpdatedAt(v time.Time) *CcgoDeviceLoginCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CcgoDeviceLoginCreate) SetNillableUpdatedAt(v *time.Time) *CcgoDeviceLoginCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (_c *CcgoDeviceLoginCreate) SetDeviceCodeHash(v string) *CcgoDeviceLoginCreate {
	_c.mutation.SetDeviceCodeHash(v)
	return _c
}

// SetUserCodeHash sets the "user_code_hash" field.
func (_c *CcgoDeviceLoginCreate) SetUserCodeHash(v string) *CcgoDeviceLoginCreate {
	_c.mutation.SetUserCodeHash(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CcgoDeviceLoginCreate) SetUserID(v int64) *CcgoDeviceLoginCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *CcgoDeviceLoginCreate) SetNillableUserID(v *int64) *CcgoDeviceLoginCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *CcgoDeviceLoginCreate) SetDeviceID(v string) *CcgoDeviceLoginCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *CcgoDeviceLoginCreate) SetNillableDeviceID(v *string) *CcgoDeviceLoginCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CcgoDeviceLoginCreate) SetStatus(v string) *CcgoDeviceLoginCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CcgoDeviceLoginCreate) SetNillableStatus(v *string) *CcgoDeviceLoginCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CcgoDeviceLoginCreate) SetExpiresAt(v time.Time) *CcgoDeviceLoginCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *CcgoDeviceLoginCreate) SetApprovedAt(v time.Time) *CcgoDeviceLoginCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *CcgoDeviceLoginCreate) SetNillableApprovedAt(v *time.Time) *CcgoDeviceLoginCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *CcgoDeviceLoginCreate) SetConsumedAt(v time.Time) *CcgoDeviceLoginCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *CcgoDeviceLoginCreate) SetNillableConsumedAt(v *time.Time) *CcgoDeviceLoginCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// Mutation returns the CcgoDeviceLoginMutation object of the builder.
func (_c *CcgoDeviceLoginCreate) Mutation() *CcgoDeviceLoginMutation {
	return _c.mutation
}

// Save creates the CcgoDeviceLogin in the database.
func (_c *CcgoDeviceLoginCreate) Save(ctx context.Context) (*CcgoDeviceLogin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CcgoDeviceLoginCreate) SaveX(ctx context.Context) *CcgoDeviceLogin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CcgoDeviceLoginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CcgoDeviceLoginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CcgoDeviceLoginCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ccgodevicelogin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ccgodevicelogin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		v := ccgodevicelogin.DefaultDeviceID
		_c.mutation.SetDeviceID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ccgodevicelogin.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CcgoDeviceLoginCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CcgoDeviceLogin.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CcgoDeviceLogin.updated_at"`)}
	}
	if _, ok := _c.mutation.DeviceCodeHash(); !ok {
		return &ValidationError{Name: "device_code_hash", err: errors.New(`ent: missing required field "CcgoDeviceLogin.device_code_hash"`)}
	}
	if v, ok := _c.mutation.DeviceCodeHash(); ok {
		if err := ccgodevicelogin.DeviceCodeHashValidator(v); err != nil {
			return &ValidationError{Name: "device_code_hash", err: fmt.Errorf(`ent: validator failed for field "CcgoDeviceLogin.device_code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserCodeHash(); !ok {
		return &ValidationError{Name: "user_code_hash", err: errors.New(`ent: missing required field "CcgoDeviceLogin.user_code_hash"`)}
	}
	if v, ok := _c.mutation.UserCodeHash(); ok {
		if err := ccgodevicelogin.UserCodeHashValidator(v); err != nil {
			return &ValidationError{Name: "user_code_hash", err: fmt.Errorf(`ent: validator failed for field "CcgoDeviceLogin.user_code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "CcgoDeviceLogin.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := ccgodevicelogin.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "CcgoDeviceLogin.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CcgoDeviceLogin.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ccgodevicelogin.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CcgoDeviceLogin.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CcgoDeviceLogin.expires_at"`)}
	}
	return nil
}

func (_c *CcgoDeviceLoginCreate) sqlSave(ctx context.Context) (*CcgoDeviceLogin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CcgoDeviceLoginCreate) createSpec() (*CcgoDeviceLogin, *sqlgraph.CreateSpec) {
	var (
		_node = &CcgoDeviceLogin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ccgodevicelogin.Table, sqlgraph.NewFieldSpec(ccgodevicelogin.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ccgodevicelogin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ccgodevicelogin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeviceCodeHash(); ok {
		_spec.SetField(ccgodevicelogin.FieldDeviceCodeHash, field.TypeString, value)
		_node.DeviceCodeHash = value
	}
	if value, ok := _c.mutation.UserCodeHash(); ok {
		_spec.SetField(ccgodevicelogin.FieldUserCodeHash, field.TypeString, value)
		_node.UserCodeHash = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(ccgodevicelogin.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(ccgodevicelogin.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ccgodevicelogin.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(ccgodevicelogin.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(ccgodevicelogin.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(ccgodevicelogin.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CcgoDeviceLogin.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CcgoDeviceLoginUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CcgoDeviceLoginCreate) OnConflict(opts ...sql.ConflictOption) *CcgoDeviceLoginUpsertOne {
	_c.conflict = opts
	return &CcgoDeviceLoginUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CcgoDeviceLogin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CcgoDeviceLoginCreate) OnConflictColumns(columns ...string) *CcgoDeviceLoginUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CcgoDeviceLoginUpsertOne{
		create: _c,
	}
}

type (
	// CcgoDeviceLoginUpsertOne is the builder for "upsert"-ing
	//  one CcgoDeviceLogin node.
	CcgoDeviceLoginUpsertOne struct {
		create *CcgoDeviceLoginCreate
	}

	// CcgoDeviceLoginUpsert is the "OnConflict" setter.
	CcgoDeviceLoginUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoDeviceLoginUpsert) SetUpdatedAt(v time.Time) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateUpdatedAt() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldUpdatedAt)
	return u
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (u *CcgoDeviceLoginUpsert) SetDeviceCodeHash(v string) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldDeviceCodeHash, v)
	return u
}

// UpdateDeviceCodeHash sets the "device_code_hash" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateDeviceCodeHash() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldDeviceCodeHash)
	return u
}

// SetUserCodeHash sets the "user_code_hash" field.
func (u *CcgoDeviceLoginUpsert) SetUserCodeHash(v string) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldUserCodeHash, v)
	return u
}

// UpdateUserCodeHash sets the "user_code_hash" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateUserCodeHash() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldUserCodeHash)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CcgoDeviceLoginUpsert) SetUserID(v int64) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateUserID() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoDeviceLoginUpsert) AddUserID(v int64) *CcgoDeviceLoginUpsert {
	u.Add(ccgodevicelogin.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *CcgoDeviceLoginUpsert) ClearUserID() *CcgoDeviceLoginUpsert {
	u.SetNull(ccgodevicelogin.FieldUserID)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *CcgoDeviceLoginUpsert) SetDeviceID(v string) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateDeviceID() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldDeviceID)
	return u
}

// SetStatus sets the "status" field.
func (u *CcgoDeviceLoginUpsert) SetStatus(v string) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateStatus() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CcgoDeviceLoginUpsert) SetExpiresAt(v time.Time) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateExpiresAt() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldExpiresAt)
	return u
}

// SetApprovedAt sets the "approved_at" field.
func (u *CcgoDeviceLoginUpsert) SetApprovedAt(v time.Time) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldApprovedAt, v)
	return u
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateApprovedAt() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldApprovedAt)
	return u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *CcgoDeviceLoginUpsert) ClearApprovedAt() *CcgoDeviceLoginUpsert {
	u.SetNull(ccgodevicelogin.FieldApprovedAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CcgoDeviceLoginUpsert) SetConsumedAt(v time.Time) *CcgoDeviceLoginUpsert {
	u.Set(ccgodevicelogin.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsert) UpdateConsumedAt() *CcgoDeviceLoginUpsert {
	u.SetExcluded(ccgodevicelogin.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CcgoDeviceLoginUpsert) ClearConsumedAt() *CcgoDeviceLoginUpsert {
	u.SetNull(ccgodevicelogin.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CcgoDeviceLogin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CcgoDeviceLoginUpsertOne) UpdateNewValues() *CcgoDeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ccgodevicelogin.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CcgoDeviceLogin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CcgoDeviceLoginUpsertOne) Ignore() *CcgoDeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CcgoDeviceLoginUpsertOne) DoNothing() *CcgoDeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CcgoDeviceLoginCreate.OnConflict
// documentation for more info.
func (u *CcgoDeviceLoginUpsertOne) Update(set func(*CcgoDeviceLoginUpsert)) *CcgoDeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CcgoDeviceLoginUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoDeviceLoginUpsertOne) SetUpdatedAt(v time.Time) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateUpdatedAt() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (u *CcgoDeviceLoginUpsertOne) SetDeviceCodeHash(v string) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetDeviceCodeHash(v)
	})
}

// UpdateDeviceCodeHash sets the "device_code_hash" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateDeviceCodeHash() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateDeviceCodeHash()
	})
}

// SetUserCodeHash sets the "user_code_hash" field.
func (u *CcgoDeviceLoginUpsertOne) SetUserCodeHash(v string) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetUserCodeHash(v)
	})
}

// UpdateUserCodeHash sets the "user_code_hash" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateUserCodeHash() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateUserCodeHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *CcgoDeviceLoginUpsertOne) SetUserID(v int64) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoDeviceLoginUpsertOne) AddUserID(v int64) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateUserID() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CcgoDeviceLoginUpsertOne) ClearUserID() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.ClearUserID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *CcgoDeviceLoginUpsertOne) SetDeviceID(v string) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateDeviceID() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateDeviceID()
	})
}

// SetStatus sets the "status" field.
func (u *CcgoDeviceLoginUpsertOne) SetStatus(v string) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateStatus() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CcgoDeviceLoginUpsertOne) SetExpiresAt(v time.Time) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateExpiresAt() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *CcgoDeviceLoginUpsertOne) SetApprovedAt(v time.Time) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateApprovedAt() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *CcgoDeviceLoginUpsertOne) ClearApprovedAt() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.ClearApprovedAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CcgoDeviceLoginUpsertOne) SetConsumedAt(v time.Time) *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertOne) UpdateConsumedAt() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CcgoDeviceLoginUpsertOne) ClearConsumedAt() *CcgoDeviceLoginUpsertOne {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *CcgoDeviceLoginUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CcgoDeviceLoginCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CcgoDeviceLoginUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CcgoDeviceLoginUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CcgoDeviceLoginUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CcgoDeviceLoginCreateBulk is the builder for creating many CcgoDeviceLogin entities in bulk.
type CcgoDeviceLoginCreateBulk struct {
	config
	err      error
	builders []*CcgoDeviceLoginCreate
	conflict []sql.ConflictOption
}

// Save creates the CcgoDeviceLogin entities in the database.
func (_c *CcgoDeviceLoginCreateBulk) Save(ctx context.Context) ([]*CcgoDeviceLogin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CcgoDeviceLogin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CcgoDeviceLoginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CcgoDeviceLoginCreateBulk) SaveX(ctx context.Context) []*CcgoDeviceLogin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CcgoDeviceLoginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CcgoDeviceLoginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CcgoDeviceLogin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CcgoDeviceLoginUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CcgoDeviceLoginCreateBulk) OnConflict(opts ...sql.ConflictOption) *CcgoDeviceLoginUpsertBulk {
	_c.conflict = opts
	return &CcgoDeviceLoginUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CcgoDeviceLogin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CcgoDeviceLoginCreateBulk) OnConflictColumns(columns ...string) *CcgoDeviceLoginUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CcgoDeviceLoginUpsertBulk{
		create: _c,
	}
}

// CcgoDeviceLoginUpsertBulk is the builder for "upsert"-ing
// a bulk of CcgoDeviceLogin nodes.
type CcgoDeviceLoginUpsertBulk struct {
	create *CcgoDeviceLoginCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CcgoDeviceLogin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CcgoDeviceLoginUpsertBulk) UpdateNewValues() *CcgoDeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ccgodevicelogin.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CcgoDeviceLogin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CcgoDeviceLoginUpsertBulk) Ignore() *CcgoDeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CcgoDeviceLoginUpsertBulk) DoNothing() *CcgoDeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CcgoDeviceLoginCreateBulk.OnConflict
// documentation for more info.
func (u *CcgoDeviceLoginUpsertBulk) Update(set func(*CcgoDeviceLoginUpsert)) *CcgoDeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CcgoDeviceLoginUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoDeviceLoginUpsertBulk) SetUpdatedAt(v time.Time) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateUpdatedAt() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (u *CcgoDeviceLoginUpsertBulk) SetDeviceCodeHash(v string) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetDeviceCodeHash(v)
	})
}

// UpdateDeviceCodeHash sets the "device_code_hash" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateDeviceCodeHash() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateDeviceCodeHash()
	})
}

// SetUserCodeHash sets the "user_code_hash" field.
func (u *CcgoDeviceLoginUpsertBulk) SetUserCodeHash(v string) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetUserCodeHash(v)
	})
}

// UpdateUserCodeHash sets the "user_code_hash" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateUserCodeHash() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateUserCodeHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *CcgoDeviceLoginUpsertBulk) SetUserID(v int64) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoDeviceLoginUpsertBulk) AddUserID(v int64) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateUserID() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CcgoDeviceLoginUpsertBulk) ClearUserID() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.ClearUserID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *CcgoDeviceLoginUpsertBulk) SetDeviceID(v string) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateDeviceID() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateDeviceID()
	})
}

// SetStatus sets the "status" field.
func (u *CcgoDeviceLoginUpsertBulk) SetStatus(v string) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateStatus() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CcgoDeviceLoginUpsertBulk) SetExpiresAt(v time.Time) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateExpiresAt() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *CcgoDeviceLoginUpsertBulk) SetApprovedAt(v time.Time) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateApprovedAt() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *CcgoDeviceLoginUpsertBulk) ClearApprovedAt() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.ClearApprovedAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CcgoDeviceLoginUpsertBulk) SetConsumedAt(v time.Time) *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CcgoDeviceLoginUpsertBulk) UpdateConsumedAt() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CcgoDeviceLoginUpsertBulk) ClearConsumedAt() *CcgoDeviceLoginUpsertBulk {
	return u.Update(func(s *CcgoDeviceLoginUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *CcgoDeviceLoginUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CcgoDeviceLoginCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CcgoDeviceLoginCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CcgoDeviceLoginUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
