// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ccgocommandaudit"
)

// CcgoCommandAuditCreate is the builder for creating a CcgoCommandAudit entity.
type CcgoCommandAuditCreate struct {
	config
	mutation *CcgoCommandAuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CcgoCommandAuditCreate) SetCreatedAt(v time.Time) *CcgoCommandAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableCreatedAt(v *time.Time) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CcgoCommandAuditCreate) SetUpdatedAt(v time.Time) *CcgoCommandAuditCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableUpdatedAt(v *time.Time) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *CcgoCommandAuditCreate) SetWorkspaceID(v int64) *CcgoCommandAuditCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CcgoCommandAuditCreate) SetUserID(v int64) *CcgoCommandAuditCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *CcgoCommandAuditCreate) SetRunID(v int64) *CcgoCommandAuditCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableRunID(v *int64) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *CcgoCommandAuditCreate) SetRequestID(v string) *CcgoCommandAuditCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetCommandHash sets the "command_hash" field.
func (_c *CcgoCommandAuditCreate) SetCommandHash(v string) *CcgoCommandAuditCreate {
	_c.mutation.SetCommandHash(v)
	return _c
}

// SetRedactedCommand sets the "redacted_command" field.
func (_c *CcgoCommandAuditCreate) SetRedactedCommand(v string) *CcgoCommandAuditCreate {
	_c.mutation.SetRedactedCommand(v)
	return _c
}

// SetNillableRedactedCommand sets the "redacted_command" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableRedactedCommand(v *string) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetRedactedCommand(*v)
	}
	return _c
}

// SetServerCwd sets the "server_cwd" field.
func (_c *CcgoCommandAuditCreate) SetServerCwd(v string) *CcgoCommandAuditCreate {
	_c.mutation.SetServerCwd(v)
	return _c
}

// SetLocalCwd sets the "local_cwd" field.
func (_c *CcgoCommandAuditCreate) SetLocalCwd(v string) *CcgoCommandAuditCreate {
	_c.mutation.SetLocalCwd(v)
	return _c
}

// SetExitCode sets the "exit_code" field.
func (_c *CcgoCommandAuditCreate) SetExitCode(v int) *CcgoCommandAuditCreate {
	_c.mutation.SetExitCode(v)
	return _c
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableExitCode(v *int) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetExitCode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CcgoCommandAuditCreate) SetStatus(v string) *CcgoCommandAuditCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableStatus(v *string) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFailureReason sets the "failure_reason" field.
func (_c *CcgoCommandAuditCreate) SetFailureReason(v string) *CcgoCommandAuditCreate {
	_c.mutation.SetFailureReason(v)
	return _c
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableFailureReason(v *string) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetFailureReason(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *CcgoCommandAuditCreate) SetStartedAt(v time.Time) *CcgoCommandAuditCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableStartedAt(v *time.Time) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *CcgoCommandAuditCreate) SetFinishedAt(v time.Time) *CcgoCommandAuditCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableFinishedAt(v *time.Time) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *CcgoCommandAuditCreate) SetDurationMs(v int64) *CcgoCommandAuditCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *CcgoCommandAuditCreate) SetNillableDurationMs(v *int64) *CcgoCommandAuditCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// Mutation returns the CcgoCommandAuditMutation object of the builder.
func (_c *CcgoCommandAuditCreate) Mutation() *CcgoCommandAuditMutation {
	return _c.mutation
}

// Save creates the CcgoCommandAudit in the database.
func (_c *CcgoCommandAuditCreate) Save(ctx context.Context) (*CcgoCommandAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CcgoCommandAuditCreate) SaveX(ctx context.Context) *CcgoCommandAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CcgoCommandAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CcgoCommandAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CcgoCommandAuditCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ccgocommandaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ccgocommandaudit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RedactedCommand(); !ok {
		v := ccgocommandaudit.DefaultRedactedCommand
		_c.mutation.SetRedactedCommand(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ccgocommandaudit.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FailureReason(); !ok {
		v := ccgocommandaudit.DefaultFailureReason
		_c.mutation.SetFailureReason(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := ccgocommandaudit.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CcgoCommandAuditCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CcgoCommandAudit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CcgoCommandAudit.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "CcgoCommandAudit.workspace_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CcgoCommandAudit.user_id"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "CcgoCommandAudit.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := ccgocommandaudit.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "CcgoCommandAudit.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CommandHash(); !ok {
		return &ValidationError{Name: "command_hash", err: errors.New(`ent: missing required field "CcgoCommandAudit.command_hash"`)}
	}
	if v, ok := _c.mutation.CommandHash(); ok {
		if err := ccgocommandaudit.CommandHashValidator(v); err != nil {
			return &ValidationError{Name: "command_hash", err: fmt.Errorf(`ent: validator failed for field "CcgoCommandAudit.command_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedactedCommand(); !ok {
		return &ValidationError{Name: "redacted_command", err: errors.New(`ent: missing required field "CcgoCommandAudit.redacted_command"`)}
	}
	if _, ok := _c.mutation.ServerCwd(); !ok {
		return &ValidationError{Name: "server_cwd", err: errors.New(`ent: missing required field "CcgoCommandAudit.server_cwd"`)}
	}
	if v, ok := _c.mutation.ServerCwd(); ok {
		if err := ccgocommandaudit.ServerCwdValidator(v); err != nil {
			return &ValidationError{Name: "server_cwd", err: fmt.Errorf(`ent: validator failed for field "CcgoCommandAudit.server_cwd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LocalCwd(); !ok {
		return &ValidationError{Name: "local_cwd", err: errors.New(`ent: missing required field "CcgoCommandAudit.local_cwd"`)}
	}
	if v, ok := _c.mutation.LocalCwd(); ok {
		if err := ccgocommandaudit.LocalCwdValidator(v); err != nil {
			return &ValidationError{Name: "local_cwd", err: fmt.Errorf(`ent: validator failed for field "CcgoCommandAudit.local_cwd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CcgoCommandAudit.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ccgocommandaudit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CcgoCommandAudit.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FailureReason(); !ok {
		return &ValidationError{Name: "failure_reason", err: errors.New(`ent: missing required field "CcgoCommandAudit.failure_reason"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "CcgoCommandAudit.duration_ms"`)}
	}
	return nil
}

func (_c *CcgoCommandAuditCreate) sqlSave(ctx context.Context) (*CcgoCommandAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CcgoCommandAuditCreate) createSpec() (*CcgoCommandAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &CcgoCommandAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ccgocommandaudit.Table, sqlgraph.NewFieldSpec(ccgocommandaudit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ccgocommandaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ccgocommandaudit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(ccgocommandaudit.FieldWorkspaceID, field.TypeInt64, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(ccgocommandaudit.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(ccgocommandaudit.FieldRunID, field.TypeInt64, value)
		_node.RunID = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(ccgocommandaudit.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.CommandHash(); ok {
		_spec.SetField(ccgocommandaudit.FieldCommandHash, field.TypeString, value)
		_node.CommandHash = value
	}
	if value, ok := _c.mutation.RedactedCommand(); ok {
		_spec.SetField(ccgocommandaudit.FieldRedactedCommand, field.TypeString, value)
		_node.RedactedCommand = value
	}
	if value, ok := _c.mutation.ServerCwd(); ok {
		_spec.SetField(ccgocommandaudit.FieldServerCwd, field.TypeString, value)
		_node.ServerCwd = value
	}
	if value, ok := _c.mutation.LocalCwd(); ok {
		_spec.SetField(ccgocommandaudit.FieldLocalCwd, field.TypeString, value)
		_node.LocalCwd = value
	}
	if value, ok := _c.mutation.ExitCode(); ok {
		_spec.SetField(ccgocommandaudit.FieldExitCode, field.TypeInt, value)
		_node.ExitCode = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ccgocommandaudit.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FailureReason(); ok {
		_spec.SetField(ccgocommandaudit.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(ccgocommandaudit.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(ccgocommandaudit.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(ccgocommandaudit.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CcgoCommandAudit.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CcgoCommandAuditUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CcgoCommandAuditCreate) OnConflict(opts ...sql.ConflictOption) *CcgoCommandAuditUpsertOne {
	_c.conflict = opts
	return &CcgoCommandAuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CcgoCommandAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CcgoCommandAuditCreate) OnConflictColumns(columns ...string) *CcgoCommandAuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CcgoCommandAuditUpsertOne{
		create: _c,
	}
}

type (
	// CcgoCommandAuditUpsertOne is the builder for "upsert"-ing
	//  one CcgoCommandAudit node.
	CcgoCommandAuditUpsertOne struct {
		create *CcgoCommandAuditCreate
	}

	// CcgoCommandAuditUpsert is the "OnConflict" setter.
	CcgoCommandAuditUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoCommandAuditUpsert) SetUpdatedAt(v time.Time) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateUpdatedAt() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldUpdatedAt)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *CcgoCommandAuditUpsert) SetWorkspaceID(v int64) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateWorkspaceID() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldWorkspaceID)
	return u
}

// AddWorkspaceID adds v to the "workspace_id" field.
func (u *CcgoCommandAuditUpsert) AddWorkspaceID(v int64) *CcgoCommandAuditUpsert {
	u.Add(ccgocommandaudit.FieldWorkspaceID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CcgoCommandAuditUpsert) SetUserID(v int64) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateUserID() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoCommandAuditUpsert) AddUserID(v int64) *CcgoCommandAuditUpsert {
	u.Add(ccgocommandaudit.FieldUserID, v)
	return u
}

// SetRunID sets the "run_id" field.
func (u *CcgoCommandAuditUpsert) SetRunID(v int64) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateRunID() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldRunID)
	return u
}

// AddRunID adds v to the "run_id" field.
func (u *CcgoCommandAuditUpsert) AddRunID(v int64) *CcgoCommandAuditUpsert {
	u.Add(ccgocommandaudit.FieldRunID, v)
	return u
}

// ClearRunID clears the value of the "run_id" field.
func (u *CcgoCommandAuditUpsert) ClearRunID() *CcgoCommandAuditUpsert {
	u.SetNull(ccgocommandaudit.FieldRunID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *CcgoCommandAuditUpsert) SetRequestID(v string) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateRequestID() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldRequestID)
	return u
}

// SetCommandHash sets the "command_hash" field.
func (u *CcgoCommandAuditUpsert) SetCommandHash(v string) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldCommandHash, v)
	return u
}

// UpdateCommandHash sets the "command_hash" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateCommandHash() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldCommandHash)
	return u
}

// SetRedactedCommand sets the "redacted_command" field.
func (u *CcgoCommandAuditUpsert) SetRedactedCommand(v string) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldRedactedCommand, v)
	return u
}

// UpdateRedactedCommand sets the "redacted_command" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateRedactedCommand() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldRedactedCommand)
	return u
}

// SetServerCwd sets the "server_cwd" field.
func (u *CcgoCommandAuditUpsert) SetServerCwd(v string) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldServerCwd, v)
	return u
}

// UpdateServerCwd sets the "server_cwd" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateServerCwd() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldServerCwd)
	return u
}

// SetLocalCwd sets the "local_cwd" field.
func (u *CcgoCommandAuditUpsert) SetLocalCwd(v string) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldLocalCwd, v)
	return u
}

// UpdateLocalCwd sets the "local_cwd" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateLocalCwd() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldLocalCwd)
	return u
}

// SetExitCode sets the "exit_code" field.
func (u *CcgoCommandAuditUpsert) SetExitCode(v int) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldExitCode, v)
	return u
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateExitCode() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldExitCode)
	return u
}

// AddExitCode adds v to the "exit_code" field.
func (u *CcgoCommandAuditUpsert) AddExitCode(v int) *CcgoCommandAuditUpsert {
	u.Add(ccgocommandaudit.FieldExitCode, v)
	return u
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *CcgoCommandAuditUpsert) ClearExitCode() *CcgoCommandAuditUpsert {
	u.SetNull(ccgocommandaudit.FieldExitCode)
	return u
}

// SetStatus sets the "status" field.
func (u *CcgoCommandAuditUpsert) SetStatus(v string) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateStatus() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldStatus)
	return u
}

// SetFailureReason sets the "failure_reason" field.
func (u *CcgoCommandAuditUpsert) SetFailureReason(v string) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldFailureReason, v)
	return u
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateFailureReason() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldFailureReason)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *CcgoCommandAuditUpsert) SetStartedAt(v time.Time) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateStartedAt() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *CcgoCommandAuditUpsert) ClearStartedAt() *CcgoCommandAuditUpsert {
	u.SetNull(ccgocommandaudit.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *CcgoCommandAuditUpsert) SetFinishedAt(v time.Time) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateFinishedAt() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *CcgoCommandAuditUpsert) ClearFinishedAt() *CcgoCommandAuditUpsert {
	u.SetNull(ccgocommandaudit.FieldFinishedAt)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *CcgoCommandAuditUpsert) SetDurationMs(v int64) *CcgoCommandAuditUpsert {
	u.Set(ccgocommandaudit.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsert) UpdateDurationMs() *CcgoCommandAuditUpsert {
	u.SetExcluded(ccgocommandaudit.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *CcgoCommandAuditUpsert) AddDurationMs(v int64) *CcgoCommandAuditUpsert {
	u.Add(ccgocommandaudit.FieldDurationMs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CcgoCommandAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CcgoCommandAuditUpsertOne) UpdateNewValues() *CcgoCommandAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ccgocommandaudit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CcgoCommandAudit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CcgoCommandAuditUpsertOne) Ignore() *CcgoCommandAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CcgoCommandAuditUpsertOne) DoNothing() *CcgoCommandAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CcgoCommandAuditCreate.OnConflict
// documentation for more info.
func (u *CcgoCommandAuditUpsertOne) Update(set func(*CcgoCommandAuditUpsert)) *CcgoCommandAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CcgoCommandAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoCommandAuditUpsertOne) SetUpdatedAt(v time.Time) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateUpdatedAt() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *CcgoCommandAuditUpsertOne) SetWorkspaceID(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetWorkspaceID(v)
	})
}

// AddWorkspaceID adds v to the "workspace_id" field.
func (u *CcgoCommandAuditUpsertOne) AddWorkspaceID(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateWorkspaceID() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CcgoCommandAuditUpsertOne) SetUserID(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoCommandAuditUpsertOne) AddUserID(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateUserID() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateUserID()
	})
}

// SetRunID sets the "run_id" field.
func (u *CcgoCommandAuditUpsertOne) SetRunID(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetRunID(v)
	})
}

// AddRunID adds v to the "run_id" field.
func (u *CcgoCommandAuditUpsertOne) AddRunID(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateRunID() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateRunID()
	})
}

// ClearRunID clears the value of the "run_id" field.
func (u *CcgoCommandAuditUpsertOne) ClearRunID() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearRunID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *CcgoCommandAuditUpsertOne) SetRequestID(v string) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateRequestID() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateRequestID()
	})
}

// SetCommandHash sets the "command_hash" field.
func (u *CcgoCommandAuditUpsertOne) SetCommandHash(v string) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetCommandHash(v)
	})
}

// UpdateCommandHash sets the "command_hash" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateCommandHash() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateCommandHash()
	})
}

// SetRedactedCommand sets the "redacted_command" field.
func (u *CcgoCommandAuditUpsertOne) SetRedactedCommand(v string) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetRedactedCommand(v)
	})
}

// UpdateRedactedCommand sets the "redacted_command" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateRedactedCommand() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateRedactedCommand()
	})
}

// SetServerCwd sets the "server_cwd" field.
func (u *CcgoCommandAuditUpsertOne) SetServerCwd(v string) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetServerCwd(v)
	})
}

// UpdateServerCwd sets the "server_cwd" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateServerCwd() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateServerCwd()
	})
}

// SetLocalCwd sets the "local_cwd" field.
func (u *CcgoCommandAuditUpsertOne) SetLocalCwd(v string) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetLocalCwd(v)
	})
}

// UpdateLocalCwd sets the "local_cwd" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateLocalCwd() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateLocalCwd()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *CcgoCommandAuditUpsertOne) SetExitCode(v int) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *CcgoCommandAuditUpsertOne) AddExitCode(v int) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateExitCode() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *CcgoCommandAuditUpsertOne) ClearExitCode() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearExitCode()
	})
}

// SetStatus sets the "status" field.
func (u *CcgoCommandAuditUpsertOne) SetStatus(v string) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateStatus() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateStatus()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *CcgoCommandAuditUpsertOne) SetFailureReason(v string) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateFailureReason() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateFailureReason()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *CcgoCommandAuditUpsertOne) SetStartedAt(v time.Time) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateStartedAt() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *CcgoCommandAuditUpsertOne) ClearStartedAt() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *CcgoCommandAuditUpsertOne) SetFinishedAt(v time.Time) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateFinishedAt() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *CcgoCommandAuditUpsertOne) ClearFinishedAt() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearFinishedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *CcgoCommandAuditUpsertOne) SetDurationMs(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *CcgoCommandAuditUpsertOne) AddDurationMs(v int64) *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertOne) UpdateDurationMs() *CcgoCommandAuditUpsertOne {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateDurationMs()
	})
}

// Exec executes the query.
func (u *CcgoCommandAuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CcgoCommandAuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CcgoCommandAuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CcgoCommandAuditUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CcgoCommandAuditUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CcgoCommandAuditCreateBulk is the builder for creating many CcgoCommandAudit entities in bulk.
type CcgoCommandAuditCreateBulk struct {
	config
	err      error
	builders []*CcgoCommandAuditCreate
	conflict []sql.ConflictOption
}

// Save creates the CcgoCommandAudit entities in the database.
func (_c *CcgoCommandAuditCreateBulk) Save(ctx context.Context) ([]*CcgoCommandAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CcgoCommandAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CcgoCommandAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CcgoCommandAuditCreateBulk) SaveX(ctx context.Context) []*CcgoCommandAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CcgoCommandAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CcgoCommandAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CcgoCommandAudit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CcgoCommandAuditUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CcgoCommandAuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *CcgoCommandAuditUpsertBulk {
	_c.conflict = opts
	return &CcgoCommandAuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CcgoCommandAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CcgoCommandAuditCreateBulk) OnConflictColumns(columns ...string) *CcgoCommandAuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CcgoCommandAuditUpsertBulk{
		create: _c,
	}
}

// CcgoCommandAuditUpsertBulk is the builder for "upsert"-ing
// a bulk of CcgoCommandAudit nodes.
type CcgoCommandAuditUpsertBulk struct {
	create *CcgoCommandAuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CcgoCommandAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CcgoCommandAuditUpsertBulk) UpdateNewValues() *CcgoCommandAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ccgocommandaudit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CcgoCommandAudit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CcgoCommandAuditUpsertBulk) Ignore() *CcgoCommandAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CcgoCommandAuditUpsertBulk) DoNothing() *CcgoCommandAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CcgoCommandAuditCreateBulk.OnConflict
// documentation for more info.
func (u *CcgoCommandAuditUpsertBulk) Update(set func(*CcgoCommandAuditUpsert)) *CcgoCommandAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CcgoCommandAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoCommandAuditUpsertBulk) SetUpdatedAt(v time.Time) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateUpdatedAt() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *CcgoCommandAuditUpsertBulk) SetWorkspaceID(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetWorkspaceID(v)
	})
}

// AddWorkspaceID adds v to the "workspace_id" field.
func (u *CcgoCommandAuditUpsertBulk) AddWorkspaceID(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateWorkspaceID() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CcgoCommandAuditUpsertBulk) SetUserID(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoCommandAuditUpsertBulk) AddUserID(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateUserID() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateUserID()
	})
}

// SetRunID sets the "run_id" field.
func (u *CcgoCommandAuditUpsertBulk) SetRunID(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetRunID(v)
	})
}

// AddRunID adds v to the "run_id" field.
func (u *CcgoCommandAuditUpsertBulk) AddRunID(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateRunID() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateRunID()
	})
}

// ClearRunID clears the value of the "run_id" field.
func (u *CcgoCommandAuditUpsertBulk) ClearRunID() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearRunID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *CcgoCommandAuditUpsertBulk) SetRequestID(v string) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateRequestID() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateRequestID()
	})
}

// SetCommandHash sets the "command_hash" field.
func (u *CcgoCommandAuditUpsertBulk) SetCommandHash(v string) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetCommandHash(v)
	})
}

// UpdateCommandHash sets the "command_hash" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateCommandHash() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateCommandHash()
	})
}

// SetRedactedCommand sets the "redacted_command" field.
func (u *CcgoCommandAuditUpsertBulk) SetRedactedCommand(v string) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetRedactedCommand(v)
	})
}

// UpdateRedactedCommand sets the "redacted_command" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateRedactedCommand() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateRedactedCommand()
	})
}

// SetServerCwd sets the "server_cwd" field.
func (u *CcgoCommandAuditUpsertBulk) SetServerCwd(v string) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetServerCwd(v)
	})
}

// UpdateServerCwd sets the "server_cwd" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateServerCwd() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateServerCwd()
	})
}

// SetLocalCwd sets the "local_cwd" field.
func (u *CcgoCommandAuditUpsertBulk) SetLocalCwd(v string) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetLocalCwd(v)
	})
}

// UpdateLocalCwd sets the "local_cwd" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateLocalCwd() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateLocalCwd()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *CcgoCommandAuditUpsertBulk) SetExitCode(v int) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *CcgoCommandAuditUpsertBulk) AddExitCode(v int) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateExitCode() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *CcgoCommandAuditUpsertBulk) ClearExitCode() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearExitCode()
	})
}

// SetStatus sets the "status" field.
func (u *CcgoCommandAuditUpsertBulk) SetStatus(v string) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateStatus() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateStatus()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *CcgoCommandAuditUpsertBulk) SetFailureReason(v string) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateFailureReason() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateFailureReason()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *CcgoCommandAuditUpsertBulk) SetStartedAt(v time.Time) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateStartedAt() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *CcgoCommandAuditUpsertBulk) ClearStartedAt() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *CcgoCommandAuditUpsertBulk) SetFinishedAt(v time.Time) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateFinishedAt() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *CcgoCommandAuditUpsertBulk) ClearFinishedAt() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.ClearFinishedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *CcgoCommandAuditUpsertBulk) SetDurationMs(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *CcgoCommandAuditUpsertBulk) AddDurationMs(v int64) *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *CcgoCommandAuditUpsertBulk) UpdateDurationMs() *CcgoCommandAuditUpsertBulk {
	return u.Update(func(s *CcgoCommandAuditUpsert) {
		s.UpdateDurationMs()
	})
}

// Exec executes the query.
func (u *CcgoCommandAuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CcgoCommandAuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CcgoCommandAuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CcgoCommandAuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
