// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ccgoagentcredential"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CcgoAgentCredentialDelete is the builder for deleting a CcgoAgentCredential entity.
type CcgoAgentCredentialDelete struct {
	config
	hooks    []Hook
	mutation *CcgoAgentCredentialMutation
}

// Where appends a list predicates to the CcgoAgentCredentialDelete builder.
func (_d *CcgoAgentCredentialDelete) Where(ps ...predicate.CcgoAgentCredential) *CcgoAgentCredentialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CcgoAgentCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CcgoAgentCredentialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CcgoAgentCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ccgoagentcredential.Table, sqlgraph.NewFieldSpec(ccgoagentcredential.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CcgoAgentCredentialDeleteOne is the builder for deleting a single CcgoAgentCredential entity.
type CcgoAgentCredentialDeleteOne struct {
	_d *CcgoAgentCredentialDelete
}

// Where appends a list predicates to the CcgoAgentCredentialDelete builder.
func (_d *CcgoAgentCredentialDeleteOne) Where(ps ...predicate.CcgoAgentCredential) *CcgoAgentCredentialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CcgoAgentCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ccgoagentcredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CcgoAgentCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
