// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ccgoworkstationrun"
)

// CcgoWorkstationRunCreate is the builder for creating a CcgoWorkstationRun entity.
type CcgoWorkstationRunCreate struct {
	config
	mutation *CcgoWorkstationRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CcgoWorkstationRunCreate) SetCreatedAt(v time.Time) *CcgoWorkstationRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableCreatedAt(v *time.Time) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CcgoWorkstationRunCreate) SetUpdatedAt(v time.Time) *CcgoWorkstationRunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableUpdatedAt(v *time.Time) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *CcgoWorkstationRunCreate) SetWorkspaceID(v int64) *CcgoWorkstationRunCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CcgoWorkstationRunCreate) SetUserID(v int64) *CcgoWorkstationRunCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *CcgoWorkstationRunCreate) SetRunID(v string) *CcgoWorkstationRunCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CcgoWorkstationRunCreate) SetStatus(v string) *CcgoWorkstationRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableStatus(v *string) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetServerPid sets the "server_pid" field.
func (_c *CcgoWorkstationRunCreate) SetServerPid(v string) *CcgoWorkstationRunCreate {
	_c.mutation.SetServerPid(v)
	return _c
}

// SetNillableServerPid sets the "server_pid" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableServerPid(v *string) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetServerPid(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *CcgoWorkstationRunCreate) SetStartedAt(v time.Time) *CcgoWorkstationRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableStartedAt(v *time.Time) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetStoppedAt sets the "stopped_at" field.
func (_c *CcgoWorkstationRunCreate) SetStoppedAt(v time.Time) *CcgoWorkstationRunCreate {
	_c.mutation.SetStoppedAt(v)
	return _c
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableStoppedAt(v *time.Time) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetStoppedAt(*v)
	}
	return _c
}

// SetStopReason sets the "stop_reason" field.
func (_c *CcgoWorkstationRunCreate) SetStopReason(v string) *CcgoWorkstationRunCreate {
	_c.mutation.SetStopReason(v)
	return _c
}

// SetNillableStopReason sets the "stop_reason" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableStopReason(v *string) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetStopReason(*v)
	}
	return _c
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_c *CcgoWorkstationRunCreate) SetLastHeartbeatAt(v time.Time) *CcgoWorkstationRunCreate {
	_c.mutation.SetLastHeartbeatAt(v)
	return _c
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_c *CcgoWorkstationRunCreate) SetNillableLastHeartbeatAt(v *time.Time) *CcgoWorkstationRunCreate {
	if v != nil {
		_c.SetLastHeartbeatAt(*v)
	}
	return _c
}

// Mutation returns the CcgoWorkstationRunMutation object of the builder.
func (_c *CcgoWorkstationRunCreate) Mutation() *CcgoWorkstationRunMutation {
	return _c.mutation
}

// Save creates the CcgoWorkstationRun in the database.
func (_c *CcgoWorkstationRunCreate) Save(ctx context.Context) (*CcgoWorkstationRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CcgoWorkstationRunCreate) SaveX(ctx context.Context) *CcgoWorkstationRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CcgoWorkstationRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CcgoWorkstationRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CcgoWorkstationRunCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ccgoworkstationrun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ccgoworkstationrun.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ccgoworkstationrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ServerPid(); !ok {
		v := ccgoworkstationrun.DefaultServerPid
		_c.mutation.SetServerPid(v)
	}
	if _, ok := _c.mutation.StopReason(); !ok {
		v := ccgoworkstationrun.DefaultStopReason
		_c.mutation.SetStopReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CcgoWorkstationRunCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CcgoWorkstationRun.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CcgoWorkstationRun.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "CcgoWorkstationRun.workspace_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CcgoWorkstationRun.user_id"`)}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "CcgoWorkstationRun.run_id"`)}
	}
	if v, ok := _c.mutation.RunID(); ok {
		if err := ccgoworkstationrun.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.run_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CcgoWorkstationRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ccgoworkstationrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServerPid(); !ok {
		return &ValidationError{Name: "server_pid", err: errors.New(`ent: missing required field "CcgoWorkstationRun.server_pid"`)}
	}
	if v, ok := _c.mutation.ServerPid(); ok {
		if err := ccgoworkstationrun.ServerPidValidator(v); err != nil {
			return &ValidationError{Name: "server_pid", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.server_pid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StopReason(); !ok {
		return &ValidationError{Name: "stop_reason", err: errors.New(`ent: missing required field "CcgoWorkstationRun.stop_reason"`)}
	}
	return nil
}

func (_c *CcgoWorkstationRunCreate) sqlSave(ctx context.Context) (*CcgoWorkstationRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CcgoWorkstationRunCreate) createSpec() (*CcgoWorkstationRun, *sqlgraph.CreateSpec) {
	var (
		_node = &CcgoWorkstationRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ccgoworkstationrun.Table, sqlgraph.NewFieldSpec(ccgoworkstationrun.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldWorkspaceID, field.TypeInt64, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ServerPid(); ok {
		_spec.SetField(ccgoworkstationrun.FieldServerPid, field.TypeString, value)
		_node.ServerPid = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.StoppedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStoppedAt, field.TypeTime, value)
		_node.StoppedAt = &value
	}
	if value, ok := _c.mutation.StopReason(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStopReason, field.TypeString, value)
		_node.StopReason = value
	}
	if value, ok := _c.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldLastHeartbeatAt, field.TypeTime, value)
		_node.LastHeartbeatAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CcgoWorkstationRun.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CcgoWorkstationRunUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CcgoWorkstationRunCreate) OnConflict(opts ...sql.ConflictOption) *CcgoWorkstationRunUpsertOne {
	_c.conflict = opts
	return &CcgoWorkstationRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CcgoWorkstationRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CcgoWorkstationRunCreate) OnConflictColumns(columns ...string) *CcgoWorkstationRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CcgoWorkstationRunUpsertOne{
		create: _c,
	}
}

type (
	// CcgoWorkstationRunUpsertOne is the builder for "upsert"-ing
	//  one CcgoWorkstationRun node.
	CcgoWorkstationRunUpsertOne struct {
		create *CcgoWorkstationRunCreate
	}

	// CcgoWorkstationRunUpsert is the "OnConflict" setter.
	CcgoWorkstationRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoWorkstationRunUpsert) SetUpdatedAt(v time.Time) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateUpdatedAt() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldUpdatedAt)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *CcgoWorkstationRunUpsert) SetWorkspaceID(v int64) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateWorkspaceID() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldWorkspaceID)
	return u
}

// AddWorkspaceID adds v to the "workspace_id" field.
func (u *CcgoWorkstationRunUpsert) AddWorkspaceID(v int64) *CcgoWorkstationRunUpsert {
	u.Add(ccgoworkstationrun.FieldWorkspaceID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CcgoWorkstationRunUpsert) SetUserID(v int64) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateUserID() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoWorkstationRunUpsert) AddUserID(v int64) *CcgoWorkstationRunUpsert {
	u.Add(ccgoworkstationrun.FieldUserID, v)
	return u
}

// SetRunID sets the "run_id" field.
func (u *CcgoWorkstationRunUpsert) SetRunID(v string) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateRunID() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldRunID)
	return u
}

// SetStatus sets the "status" field.
func (u *CcgoWorkstationRunUpsert) SetStatus(v string) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateStatus() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldStatus)
	return u
}

// SetServerPid sets the "server_pid" field.
func (u *CcgoWorkstationRunUpsert) SetServerPid(v string) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldServerPid, v)
	return u
}

// UpdateServerPid sets the "server_pid" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateServerPid() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldServerPid)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *CcgoWorkstationRunUpsert) SetStartedAt(v time.Time) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateStartedAt() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *CcgoWorkstationRunUpsert) ClearStartedAt() *CcgoWorkstationRunUpsert {
	u.SetNull(ccgoworkstationrun.FieldStartedAt)
	return u
}

// SetStoppedAt sets the "stopped_at" field.
func (u *CcgoWorkstationRunUpsert) SetStoppedAt(v time.Time) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldStoppedAt, v)
	return u
}

// UpdateStoppedAt sets the "stopped_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateStoppedAt() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldStoppedAt)
	return u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (u *CcgoWorkstationRunUpsert) ClearStoppedAt() *CcgoWorkstationRunUpsert {
	u.SetNull(ccgoworkstationrun.FieldStoppedAt)
	return u
}

// SetStopReason sets the "stop_reason" field.
func (u *CcgoWorkstationRunUpsert) SetStopReason(v string) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldStopReason, v)
	return u
}

// UpdateStopReason sets the "stop_reason" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateStopReason() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldStopReason)
	return u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (u *CcgoWorkstationRunUpsert) SetLastHeartbeatAt(v time.Time) *CcgoWorkstationRunUpsert {
	u.Set(ccgoworkstationrun.FieldLastHeartbeatAt, v)
	return u
}

// UpdateLastHeartbeatAt sets the "last_heartbeat_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsert) UpdateLastHeartbeatAt() *CcgoWorkstationRunUpsert {
	u.SetExcluded(ccgoworkstationrun.FieldLastHeartbeatAt)
	return u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (u *CcgoWorkstationRunUpsert) ClearLastHeartbeatAt() *CcgoWorkstationRunUpsert {
	u.SetNull(ccgoworkstationrun.FieldLastHeartbeatAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CcgoWorkstationRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CcgoWorkstationRunUpsertOne) UpdateNewValues() *CcgoWorkstationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ccgoworkstationrun.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CcgoWorkstationRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CcgoWorkstationRunUpsertOne) Ignore() *CcgoWorkstationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CcgoWorkstationRunUpsertOne) DoNothing() *CcgoWorkstationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CcgoWorkstationRunCreate.OnConflict
// documentation for more info.
func (u *CcgoWorkstationRunUpsertOne) Update(set func(*CcgoWorkstationRunUpsert)) *CcgoWorkstationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CcgoWorkstationRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoWorkstationRunUpsertOne) SetUpdatedAt(v time.Time) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateUpdatedAt() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *CcgoWorkstationRunUpsertOne) SetWorkspaceID(v int64) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetWorkspaceID(v)
	})
}

// AddWorkspaceID adds v to the "workspace_id" field.
func (u *CcgoWorkstationRunUpsertOne) AddWorkspaceID(v int64) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.AddWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateWorkspaceID() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CcgoWorkstationRunUpsertOne) SetUserID(v int64) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoWorkstationRunUpsertOne) AddUserID(v int64) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateUserID() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateUserID()
	})
}

// SetRunID sets the "run_id" field.
func (u *CcgoWorkstationRunUpsertOne) SetRunID(v string) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateRunID() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateRunID()
	})
}

// SetStatus sets the "status" field.
func (u *CcgoWorkstationRunUpsertOne) SetStatus(v string) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateStatus() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStatus()
	})
}

// SetServerPid sets the "server_pid" field.
func (u *CcgoWorkstationRunUpsertOne) SetServerPid(v string) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetServerPid(v)
	})
}

// UpdateServerPid sets the "server_pid" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateServerPid() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateServerPid()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *CcgoWorkstationRunUpsertOne) SetStartedAt(v time.Time) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateStartedAt() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *CcgoWorkstationRunUpsertOne) ClearStartedAt() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.ClearStartedAt()
	})
}

// SetStoppedAt sets the "stopped_at" field.
func (u *CcgoWorkstationRunUpsertOne) SetStoppedAt(v time.Time) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStoppedAt(v)
	})
}

// UpdateStoppedAt sets the "stopped_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateStoppedAt() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStoppedAt()
	})
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (u *CcgoWorkstationRunUpsertOne) ClearStoppedAt() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.ClearStoppedAt()
	})
}

// SetStopReason sets the "stop_reason" field.
func (u *CcgoWorkstationRunUpsertOne) SetStopReason(v string) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStopReason(v)
	})
}

// UpdateStopReason sets the "stop_reason" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateStopReason() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStopReason()
	})
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (u *CcgoWorkstationRunUpsertOne) SetLastHeartbeatAt(v time.Time) *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetLastHeartbeatAt(v)
	})
}

// UpdateLastHeartbeatAt sets the "last_heartbeat_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertOne) UpdateLastHeartbeatAt() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateLastHeartbeatAt()
	})
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (u *CcgoWorkstationRunUpsertOne) ClearLastHeartbeatAt() *CcgoWorkstationRunUpsertOne {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.ClearLastHeartbeatAt()
	})
}

// Exec executes the query.
func (u *CcgoWorkstationRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CcgoWorkstationRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CcgoWorkstationRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CcgoWorkstationRunUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CcgoWorkstationRunUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CcgoWorkstationRunCreateBulk is the builder for creating many CcgoWorkstationRun entities in bulk.
type CcgoWorkstationRunCreateBulk struct {
	config
	err      error
	builders []*CcgoWorkstationRunCreate
	conflict []sql.ConflictOption
}

// Save creates the CcgoWorkstationRun entities in the database.
func (_c *CcgoWorkstationRunCreateBulk) Save(ctx context.Context) ([]*CcgoWorkstationRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CcgoWorkstationRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CcgoWorkstationRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CcgoWorkstationRunCreateBulk) SaveX(ctx context.Context) []*CcgoWorkstationRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CcgoWorkstationRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CcgoWorkstationRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CcgoWorkstationRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CcgoWorkstationRunUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CcgoWorkstationRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *CcgoWorkstationRunUpsertBulk {
	_c.conflict = opts
	return &CcgoWorkstationRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CcgoWorkstationRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CcgoWorkstationRunCreateBulk) OnConflictColumns(columns ...string) *CcgoWorkstationRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CcgoWorkstationRunUpsertBulk{
		create: _c,
	}
}

// CcgoWorkstationRunUpsertBulk is the builder for "upsert"-ing
// a bulk of CcgoWorkstationRun nodes.
type CcgoWorkstationRunUpsertBulk struct {
	create *CcgoWorkstationRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CcgoWorkstationRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CcgoWorkstationRunUpsertBulk) UpdateNewValues() *CcgoWorkstationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ccgoworkstationrun.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CcgoWorkstationRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CcgoWorkstationRunUpsertBulk) Ignore() *CcgoWorkstationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CcgoWorkstationRunUpsertBulk) DoNothing() *CcgoWorkstationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CcgoWorkstationRunCreateBulk.OnConflict
// documentation for more info.
func (u *CcgoWorkstationRunUpsertBulk) Update(set func(*CcgoWorkstationRunUpsert)) *CcgoWorkstationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CcgoWorkstationRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CcgoWorkstationRunUpsertBulk) SetUpdatedAt(v time.Time) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateUpdatedAt() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *CcgoWorkstationRunUpsertBulk) SetWorkspaceID(v int64) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetWorkspaceID(v)
	})
}

// AddWorkspaceID adds v to the "workspace_id" field.
func (u *CcgoWorkstationRunUpsertBulk) AddWorkspaceID(v int64) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.AddWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateWorkspaceID() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CcgoWorkstationRunUpsertBulk) SetUserID(v int64) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CcgoWorkstationRunUpsertBulk) AddUserID(v int64) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateUserID() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateUserID()
	})
}

// SetRunID sets the "run_id" field.
func (u *CcgoWorkstationRunUpsertBulk) SetRunID(v string) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateRunID() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateRunID()
	})
}

// SetStatus sets the "status" field.
func (u *CcgoWorkstationRunUpsertBulk) SetStatus(v string) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateStatus() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStatus()
	})
}

// SetServerPid sets the "server_pid" field.
func (u *CcgoWorkstationRunUpsertBulk) SetServerPid(v string) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetServerPid(v)
	})
}

// UpdateServerPid sets the "server_pid" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateServerPid() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateServerPid()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *CcgoWorkstationRunUpsertBulk) SetStartedAt(v time.Time) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateStartedAt() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *CcgoWorkstationRunUpsertBulk) ClearStartedAt() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.ClearStartedAt()
	})
}

// SetStoppedAt sets the "stopped_at" field.
func (u *CcgoWorkstationRunUpsertBulk) SetStoppedAt(v time.Time) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStoppedAt(v)
	})
}

// UpdateStoppedAt sets the "stopped_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateStoppedAt() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStoppedAt()
	})
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (u *CcgoWorkstationRunUpsertBulk) ClearStoppedAt() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.ClearStoppedAt()
	})
}

// SetStopReason sets the "stop_reason" field.
func (u *CcgoWorkstationRunUpsertBulk) SetStopReason(v string) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetStopReason(v)
	})
}

// UpdateStopReason sets the "stop_reason" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateStopReason() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateStopReason()
	})
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (u *CcgoWorkstationRunUpsertBulk) SetLastHeartbeatAt(v time.Time) *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.SetLastHeartbeatAt(v)
	})
}

// UpdateLastHeartbeatAt sets the "last_heartbeat_at" field to the value that was provided on create.
func (u *CcgoWorkstationRunUpsertBulk) UpdateLastHeartbeatAt() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.UpdateLastHeartbeatAt()
	})
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (u *CcgoWorkstationRunUpsertBulk) ClearLastHeartbeatAt() *CcgoWorkstationRunUpsertBulk {
	return u.Update(func(s *CcgoWorkstationRunUpsert) {
		s.ClearLastHeartbeatAt()
	})
}

// Exec executes the query.
func (u *CcgoWorkstationRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CcgoWorkstationRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CcgoWorkstationRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CcgoWorkstationRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
