// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ccgoworkspace"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CcgoWorkspaceUpdate is the builder for updating CcgoWorkspace entities.
type CcgoWorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *CcgoWorkspaceMutation
}

// Where appends a list predicates to the CcgoWorkspaceUpdate builder.
func (_u *CcgoWorkspaceUpdate) Where(ps ...predicate.CcgoWorkspace) *CcgoWorkspaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CcgoWorkspaceUpdate) SetUpdatedAt(v time.Time) *CcgoWorkspaceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CcgoWorkspaceUpdate) SetUserID(v int64) *CcgoWorkspaceUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableUserID(v *int64) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CcgoWorkspaceUpdate) AddUserID(v int64) *CcgoWorkspaceUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetWorkspaceSlug sets the "workspace_slug" field.
func (_u *CcgoWorkspaceUpdate) SetWorkspaceSlug(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetWorkspaceSlug(v)
	return _u
}

// SetNillableWorkspaceSlug sets the "workspace_slug" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableWorkspaceSlug(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetWorkspaceSlug(*v)
	}
	return _u
}

// SetServerRoot sets the "server_root" field.
func (_u *CcgoWorkspaceUpdate) SetServerRoot(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetServerRoot(v)
	return _u
}

// SetNillableServerRoot sets the "server_root" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableServerRoot(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetServerRoot(*v)
	}
	return _u
}

// SetLocalRootHash sets the "local_root_hash" field.
func (_u *CcgoWorkspaceUpdate) SetLocalRootHash(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetLocalRootHash(v)
	return _u
}

// SetNillableLocalRootHash sets the "local_root_hash" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableLocalRootHash(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetLocalRootHash(*v)
	}
	return _u
}

// SetLocalRootDisplay sets the "local_root_display" field.
func (_u *CcgoWorkspaceUpdate) SetLocalRootDisplay(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetLocalRootDisplay(v)
	return _u
}

// SetNillableLocalRootDisplay sets the "local_root_display" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableLocalRootDisplay(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetLocalRootDisplay(*v)
	}
	return _u
}

// SetLocalRootRedacted sets the "local_root_redacted" field.
func (_u *CcgoWorkspaceUpdate) SetLocalRootRedacted(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetLocalRootRedacted(v)
	return _u
}

// SetNillableLocalRootRedacted sets the "local_root_redacted" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableLocalRootRedacted(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetLocalRootRedacted(*v)
	}
	return _u
}

// SetOs sets the "os" field.
func (_u *CcgoWorkspaceUpdate) SetOs(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableOs(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// SetPathStyle sets the "path_style" field.
func (_u *CcgoWorkspaceUpdate) SetPathStyle(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetPathStyle(v)
	return _u
}

// SetNillablePathStyle sets the "path_style" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillablePathStyle(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetPathStyle(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *CcgoWorkspaceUpdate) SetDeviceID(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableDeviceID(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CcgoWorkspaceUpdate) SetStatus(v string) *CcgoWorkspaceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableStatus(v *string) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *CcgoWorkspaceUpdate) SetLastSeenAt(v time.Time) *CcgoWorkspaceUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdate) SetNillableLastSeenAt(v *time.Time) *CcgoWorkspaceUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *CcgoWorkspaceUpdate) ClearLastSeenAt() *CcgoWorkspaceUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// Mutation returns the CcgoWorkspaceMutation object of the builder.
func (_u *CcgoWorkspaceUpdate) Mutation() *CcgoWorkspaceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CcgoWorkspaceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CcgoWorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CcgoWorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CcgoWorkspaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CcgoWorkspaceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ccgoworkspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CcgoWorkspaceUpdate) check() error {
	if v, ok := _u.mutation.WorkspaceSlug(); ok {
		if err := ccgoworkspace.WorkspaceSlugValidator(v); err != nil {
			return &ValidationError{Name: "workspace_slug", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.workspace_slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerRoot(); ok {
		if err := ccgoworkspace.ServerRootValidator(v); err != nil {
			return &ValidationError{Name: "server_root", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.server_root": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalRootHash(); ok {
		if err := ccgoworkspace.LocalRootHashValidator(v); err != nil {
			return &ValidationError{Name: "local_root_hash", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.local_root_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalRootDisplay(); ok {
		if err := ccgoworkspace.LocalRootDisplayValidator(v); err != nil {
			return &ValidationError{Name: "local_root_display", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.local_root_display": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Os(); ok {
		if err := ccgoworkspace.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.os": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PathStyle(); ok {
		if err := ccgoworkspace.PathStyleValidator(v); err != nil {
			return &ValidationError{Name: "path_style", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.path_style": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := ccgoworkspace.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ccgoworkspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CcgoWorkspaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ccgoworkspace.Table, ccgoworkspace.Columns, sqlgraph.NewFieldSpec(ccgoworkspace.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ccgoworkspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ccgoworkspace.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(ccgoworkspace.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkspaceSlug(); ok {
		_spec.SetField(ccgoworkspace.FieldWorkspaceSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerRoot(); ok {
		_spec.SetField(ccgoworkspace.FieldServerRoot, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalRootHash(); ok {
		_spec.SetField(ccgoworkspace.FieldLocalRootHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalRootDisplay(); ok {
		_spec.SetField(ccgoworkspace.FieldLocalRootDisplay, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalRootRedacted(); ok {
		_spec.SetField(ccgoworkspace.FieldLocalRootRedacted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(ccgoworkspace.FieldOs, field.TypeString, value)
	}
	if value, ok := _u.mutation.PathStyle(); ok {
		_spec.SetField(ccgoworkspace.FieldPathStyle, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(ccgoworkspace.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ccgoworkspace.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(ccgoworkspace.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(ccgoworkspace.FieldLastSeenAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ccgoworkspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CcgoWorkspaceUpdateOne is the builder for updating a single CcgoWorkspace entity.
type CcgoWorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CcgoWorkspaceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CcgoWorkspaceUpdateOne) SetUpdatedAt(v time.Time) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CcgoWorkspaceUpdateOne) SetUserID(v int64) *CcgoWorkspaceUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableUserID(v *int64) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CcgoWorkspaceUpdateOne) AddUserID(v int64) *CcgoWorkspaceUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetWorkspaceSlug sets the "workspace_slug" field.
func (_u *CcgoWorkspaceUpdateOne) SetWorkspaceSlug(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetWorkspaceSlug(v)
	return _u
}

// SetNillableWorkspaceSlug sets the "workspace_slug" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableWorkspaceSlug(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetWorkspaceSlug(*v)
	}
	return _u
}

// SetServerRoot sets the "server_root" field.
func (_u *CcgoWorkspaceUpdateOne) SetServerRoot(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetServerRoot(v)
	return _u
}

// SetNillableServerRoot sets the "server_root" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableServerRoot(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetServerRoot(*v)
	}
	return _u
}

// SetLocalRootHash sets the "local_root_hash" field.
func (_u *CcgoWorkspaceUpdateOne) SetLocalRootHash(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetLocalRootHash(v)
	return _u
}

// SetNillableLocalRootHash sets the "local_root_hash" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableLocalRootHash(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetLocalRootHash(*v)
	}
	return _u
}

// SetLocalRootDisplay sets the "local_root_display" field.
func (_u *CcgoWorkspaceUpdateOne) SetLocalRootDisplay(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetLocalRootDisplay(v)
	return _u
}

// SetNillableLocalRootDisplay sets the "local_root_display" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableLocalRootDisplay(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetLocalRootDisplay(*v)
	}
	return _u
}

// SetLocalRootRedacted sets the "local_root_redacted" field.
func (_u *CcgoWorkspaceUpdateOne) SetLocalRootRedacted(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetLocalRootRedacted(v)
	return _u
}

// SetNillableLocalRootRedacted sets the "local_root_redacted" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableLocalRootRedacted(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetLocalRootRedacted(*v)
	}
	return _u
}

// SetOs sets the "os" field.
func (_u *CcgoWorkspaceUpdateOne) SetOs(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableOs(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// SetPathStyle sets the "path_style" field.
func (_u *CcgoWorkspaceUpdateOne) SetPathStyle(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetPathStyle(v)
	return _u
}

// SetNillablePathStyle sets the "path_style" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillablePathStyle(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetPathStyle(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *CcgoWorkspaceUpdateOne) SetDeviceID(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableDeviceID(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CcgoWorkspaceUpdateOne) SetStatus(v string) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableStatus(v *string) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *CcgoWorkspaceUpdateOne) SetLastSeenAt(v time.Time) *CcgoWorkspaceUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *CcgoWorkspaceUpdateOne) SetNillableLastSeenAt(v *time.Time) *CcgoWorkspaceUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *CcgoWorkspaceUpdateOne) ClearLastSeenAt() *CcgoWorkspaceUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// Mutation returns the CcgoWorkspaceMutation object of the builder.
func (_u *CcgoWorkspaceUpdateOne) Mutation() *CcgoWorkspaceMutation {
	return _u.mutation
}

// Where appends a list predicates to the CcgoWorkspaceUpdate builder.
func (_u *CcgoWorkspaceUpdateOne) Where(ps ...predicate.CcgoWorkspace) *CcgoWorkspaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CcgoWorkspaceUpdateOne) Select(field string, fields ...string) *CcgoWorkspaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CcgoWorkspace entity.
func (_u *CcgoWorkspaceUpdateOne) Save(ctx context.Context) (*CcgoWorkspace, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CcgoWorkspaceUpdateOne) SaveX(ctx context.Context) *CcgoWorkspace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CcgoWorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CcgoWorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CcgoWorkspaceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ccgoworkspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CcgoWorkspaceUpdateOne) check() error {
	if v, ok := _u.mutation.WorkspaceSlug(); ok {
		if err := ccgoworkspace.WorkspaceSlugValidator(v); err != nil {
			return &ValidationError{Name: "workspace_slug", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.workspace_slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerRoot(); ok {
		if err := ccgoworkspace.ServerRootValidator(v); err != nil {
			return &ValidationError{Name: "server_root", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.server_root": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalRootHash(); ok {
		if err := ccgoworkspace.LocalRootHashValidator(v); err != nil {
			return &ValidationError{Name: "local_root_hash", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.local_root_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalRootDisplay(); ok {
		if err := ccgoworkspace.LocalRootDisplayValidator(v); err != nil {
			return &ValidationError{Name: "local_root_display", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.local_root_display": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Os(); ok {
		if err := ccgoworkspace.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.os": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PathStyle(); ok {
		if err := ccgoworkspace.PathStyleValidator(v); err != nil {
			return &ValidationError{Name: "path_style", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.path_style": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := ccgoworkspace.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ccgoworkspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkspace.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CcgoWorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *CcgoWorkspace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ccgoworkspace.Table, ccgoworkspace.Columns, sqlgraph.NewFieldSpec(ccgoworkspace.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CcgoWorkspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ccgoworkspace.FieldID)
		for _, f := range fields {
			if !ccgoworkspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ccgoworkspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ccgoworkspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ccgoworkspace.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(ccgoworkspace.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkspaceSlug(); ok {
		_spec.SetField(ccgoworkspace.FieldWorkspaceSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerRoot(); ok {
		_spec.SetField(ccgoworkspace.FieldServerRoot, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalRootHash(); ok {
		_spec.SetField(ccgoworkspace.FieldLocalRootHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalRootDisplay(); ok {
		_spec.SetField(ccgoworkspace.FieldLocalRootDisplay, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalRootRedacted(); ok {
		_spec.SetField(ccgoworkspace.FieldLocalRootRedacted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(ccgoworkspace.FieldOs, field.TypeString, value)
	}
	if value, ok := _u.mutation.PathStyle(); ok {
		_spec.SetField(ccgoworkspace.FieldPathStyle, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(ccgoworkspace.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ccgoworkspace.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(ccgoworkspace.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(ccgoworkspace.FieldLastSeenAt, field.TypeTime)
	}
	_node = &CcgoWorkspace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ccgoworkspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
