// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ccgoworkstationrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CcgoWorkstationRunUpdate is the builder for updating CcgoWorkstationRun entities.
type CcgoWorkstationRunUpdate struct {
	config
	hooks    []Hook
	mutation *CcgoWorkstationRunMutation
}

// Where appends a list predicates to the CcgoWorkstationRunUpdate builder.
func (_u *CcgoWorkstationRunUpdate) Where(ps ...predicate.CcgoWorkstationRun) *CcgoWorkstationRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CcgoWorkstationRunUpdate) SetUpdatedAt(v time.Time) *CcgoWorkstationRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *CcgoWorkstationRunUpdate) SetWorkspaceID(v int64) *CcgoWorkstationRunUpdate {
	_u.mutation.ResetWorkspaceID()
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableWorkspaceID(v *int64) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// AddWorkspaceID adds value to the "workspace_id" field.
func (_u *CcgoWorkstationRunUpdate) AddWorkspaceID(v int64) *CcgoWorkstationRunUpdate {
	_u.mutation.AddWorkspaceID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CcgoWorkstationRunUpdate) SetUserID(v int64) *CcgoWorkstationRunUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableUserID(v *int64) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CcgoWorkstationRunUpdate) AddUserID(v int64) *CcgoWorkstationRunUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *CcgoWorkstationRunUpdate) SetRunID(v string) *CcgoWorkstationRunUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableRunID(v *string) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CcgoWorkstationRunUpdate) SetStatus(v string) *CcgoWorkstationRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableStatus(v *string) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetServerPid sets the "server_pid" field.
func (_u *CcgoWorkstationRunUpdate) SetServerPid(v string) *CcgoWorkstationRunUpdate {
	_u.mutation.SetServerPid(v)
	return _u
}

// SetNillableServerPid sets the "server_pid" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableServerPid(v *string) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetServerPid(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CcgoWorkstationRunUpdate) SetStartedAt(v time.Time) *CcgoWorkstationRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableStartedAt(v *time.Time) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CcgoWorkstationRunUpdate) ClearStartedAt() *CcgoWorkstationRunUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *CcgoWorkstationRunUpdate) SetStoppedAt(v time.Time) *CcgoWorkstationRunUpdate {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableStoppedAt(v *time.Time) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *CcgoWorkstationRunUpdate) ClearStoppedAt() *CcgoWorkstationRunUpdate {
	_u.mutation.ClearStoppedAt()
	return _u
}

// SetStopReason sets the "stop_reason" field.
func (_u *CcgoWorkstationRunUpdate) SetStopReason(v string) *CcgoWorkstationRunUpdate {
	_u.mutation.SetStopReason(v)
	return _u
}

// SetNillableStopReason sets the "stop_reason" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableStopReason(v *string) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetStopReason(*v)
	}
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *CcgoWorkstationRunUpdate) SetLastHeartbeatAt(v time.Time) *CcgoWorkstationRunUpdate {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdate) SetNillableLastHeartbeatAt(v *time.Time) *CcgoWorkstationRunUpdate {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (_u *CcgoWorkstationRunUpdate) ClearLastHeartbeatAt() *CcgoWorkstationRunUpdate {
	_u.mutation.ClearLastHeartbeatAt()
	return _u
}

// Mutation returns the CcgoWorkstationRunMutation object of the builder.
func (_u *CcgoWorkstationRunUpdate) Mutation() *CcgoWorkstationRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CcgoWorkstationRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CcgoWorkstationRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CcgoWorkstationRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CcgoWorkstationRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CcgoWorkstationRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ccgoworkstationrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CcgoWorkstationRunUpdate) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := ccgoworkstationrun.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ccgoworkstationrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerPid(); ok {
		if err := ccgoworkstationrun.ServerPidValidator(v); err != nil {
			return &ValidationError{Name: "server_pid", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.server_pid": %w`, err)}
		}
	}
	return nil
}

func (_u *CcgoWorkstationRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ccgoworkstationrun.Table, ccgoworkstationrun.Columns, sqlgraph.NewFieldSpec(ccgoworkstationrun.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(ccgoworkstationrun.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(ccgoworkstationrun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerPid(); ok {
		_spec.SetField(ccgoworkstationrun.FieldServerPid, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(ccgoworkstationrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(ccgoworkstationrun.FieldStoppedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StopReason(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStopReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatAtCleared() {
		_spec.ClearField(ccgoworkstationrun.FieldLastHeartbeatAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ccgoworkstationrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CcgoWorkstationRunUpdateOne is the builder for updating a single CcgoWorkstationRun entity.
type CcgoWorkstationRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CcgoWorkstationRunMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CcgoWorkstationRunUpdateOne) SetUpdatedAt(v time.Time) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *CcgoWorkstationRunUpdateOne) SetWorkspaceID(v int64) *CcgoWorkstationRunUpdateOne {
	_u.mutation.ResetWorkspaceID()
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableWorkspaceID(v *int64) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// AddWorkspaceID adds value to the "workspace_id" field.
func (_u *CcgoWorkstationRunUpdateOne) AddWorkspaceID(v int64) *CcgoWorkstationRunUpdateOne {
	_u.mutation.AddWorkspaceID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CcgoWorkstationRunUpdateOne) SetUserID(v int64) *CcgoWorkstationRunUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableUserID(v *int64) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CcgoWorkstationRunUpdateOne) AddUserID(v int64) *CcgoWorkstationRunUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *CcgoWorkstationRunUpdateOne) SetRunID(v string) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableRunID(v *string) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CcgoWorkstationRunUpdateOne) SetStatus(v string) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableStatus(v *string) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetServerPid sets the "server_pid" field.
func (_u *CcgoWorkstationRunUpdateOne) SetServerPid(v string) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetServerPid(v)
	return _u
}

// SetNillableServerPid sets the "server_pid" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableServerPid(v *string) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetServerPid(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CcgoWorkstationRunUpdateOne) SetStartedAt(v time.Time) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableStartedAt(v *time.Time) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CcgoWorkstationRunUpdateOne) ClearStartedAt() *CcgoWorkstationRunUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *CcgoWorkstationRunUpdateOne) SetStoppedAt(v time.Time) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableStoppedAt(v *time.Time) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *CcgoWorkstationRunUpdateOne) ClearStoppedAt() *CcgoWorkstationRunUpdateOne {
	_u.mutation.ClearStoppedAt()
	return _u
}

// SetStopReason sets the "stop_reason" field.
func (_u *CcgoWorkstationRunUpdateOne) SetStopReason(v string) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetStopReason(v)
	return _u
}

// SetNillableStopReason sets the "stop_reason" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableStopReason(v *string) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetStopReason(*v)
	}
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *CcgoWorkstationRunUpdateOne) SetLastHeartbeatAt(v time.Time) *CcgoWorkstationRunUpdateOne {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *CcgoWorkstationRunUpdateOne) SetNillableLastHeartbeatAt(v *time.Time) *CcgoWorkstationRunUpdateOne {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (_u *CcgoWorkstationRunUpdateOne) ClearLastHeartbeatAt() *CcgoWorkstationRunUpdateOne {
	_u.mutation.ClearLastHeartbeatAt()
	return _u
}

// Mutation returns the CcgoWorkstationRunMutation object of the builder.
func (_u *CcgoWorkstationRunUpdateOne) Mutation() *CcgoWorkstationRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the CcgoWorkstationRunUpdate builder.
func (_u *CcgoWorkstationRunUpdateOne) Where(ps ...predicate.CcgoWorkstationRun) *CcgoWorkstationRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CcgoWorkstationRunUpdateOne) Select(field string, fields ...string) *CcgoWorkstationRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CcgoWorkstationRun entity.
func (_u *CcgoWorkstationRunUpdateOne) Save(ctx context.Context) (*CcgoWorkstationRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CcgoWorkstationRunUpdateOne) SaveX(ctx context.Context) *CcgoWorkstationRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CcgoWorkstationRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CcgoWorkstationRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CcgoWorkstationRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ccgoworkstationrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CcgoWorkstationRunUpdateOne) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := ccgoworkstationrun.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ccgoworkstationrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerPid(); ok {
		if err := ccgoworkstationrun.ServerPidValidator(v); err != nil {
			return &ValidationError{Name: "server_pid", err: fmt.Errorf(`ent: validator failed for field "CcgoWorkstationRun.server_pid": %w`, err)}
		}
	}
	return nil
}

func (_u *CcgoWorkstationRunUpdateOne) sqlSave(ctx context.Context) (_node *CcgoWorkstationRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ccgoworkstationrun.Table, ccgoworkstationrun.Columns, sqlgraph.NewFieldSpec(ccgoworkstationrun.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CcgoWorkstationRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ccgoworkstationrun.FieldID)
		for _, f := range fields {
			if !ccgoworkstationrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ccgoworkstationrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(ccgoworkstationrun.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(ccgoworkstationrun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(ccgoworkstationrun.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerPid(); ok {
		_spec.SetField(ccgoworkstationrun.FieldServerPid, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(ccgoworkstationrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(ccgoworkstationrun.FieldStoppedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StopReason(); ok {
		_spec.SetField(ccgoworkstationrun.FieldStopReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(ccgoworkstationrun.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatAtCleared() {
		_spec.ClearField(ccgoworkstationrun.FieldLastHeartbeatAt, field.TypeTime)
	}
	_node = &CcgoWorkstationRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ccgoworkstationrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
