// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resourcesupplyledger"
)

// ResourceSupplyLedgerCreate is the builder for creating a ResourceSupplyLedger entity.
type ResourceSupplyLedgerCreate struct {
	config
	mutation *ResourceSupplyLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceSupplyLedgerCreate) SetCreatedAt(v time.Time) *ResourceSupplyLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableCreatedAt(v *time.Time) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceSupplyLedgerCreate) SetUpdatedAt(v time.Time) *ResourceSupplyLedgerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableUpdatedAt(v *time.Time) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *ResourceSupplyLedgerCreate) SetOwnerUserID(v int64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetCallerUserID sets the "caller_user_id" field.
func (_c *ResourceSupplyLedgerCreate) SetCallerUserID(v int64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetCallerUserID(v)
	return _c
}

// SetNillableCallerUserID sets the "caller_user_id" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableCallerUserID(v *int64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetCallerUserID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ResourceSupplyLedgerCreate) SetAPIKeyID(v int64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableAPIKeyID(v *int64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ResourceSupplyLedgerCreate) SetGroupID(v int64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableGroupID(v *int64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ResourceSupplyLedgerCreate) SetAccountID(v int64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableAccountID(v *int64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetUsageBillingEventID sets the "usage_billing_event_id" field.
func (_c *ResourceSupplyLedgerCreate) SetUsageBillingEventID(v int64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetUsageBillingEventID(v)
	return _c
}

// SetNillableUsageBillingEventID sets the "usage_billing_event_id" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableUsageBillingEventID(v *int64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetUsageBillingEventID(*v)
	}
	return _c
}

// SetLedgerType sets the "ledger_type" field.
func (_c *ResourceSupplyLedgerCreate) SetLedgerType(v string) *ResourceSupplyLedgerCreate {
	_c.mutation.SetLedgerType(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *ResourceSupplyLedgerCreate) SetIdempotencyKey(v string) *ResourceSupplyLedgerCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableIdempotencyKey(v *string) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ResourceSupplyLedgerCreate) SetAmount(v float64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableAmount(v *float64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *ResourceSupplyLedgerCreate) SetBalanceAfter(v float64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableBalanceAfter(v *float64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *ResourceSupplyLedgerCreate) SetActualCost(v float64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableActualCost(v *float64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetActualCost(*v)
	}
	return _c
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (_c *ResourceSupplyLedgerCreate) SetRewardMultiplier(v float64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetRewardMultiplier(v)
	return _c
}

// SetNillableRewardMultiplier sets the "reward_multiplier" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableRewardMultiplier(v *float64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetRewardMultiplier(*v)
	}
	return _c
}

// SetBillingType sets the "billing_type" field.
func (_c *ResourceSupplyLedgerCreate) SetBillingType(v int8) *ResourceSupplyLedgerCreate {
	_c.mutation.SetBillingType(v)
	return _c
}

// SetNillableBillingType sets the "billing_type" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableBillingType(v *int8) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetBillingType(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ResourceSupplyLedgerCreate) SetModel(v string) *ResourceSupplyLedgerCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableModel(v *string) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *ResourceSupplyLedgerCreate) SetRequestID(v string) *ResourceSupplyLedgerCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableRequestID(v *string) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetAdminUserID sets the "admin_user_id" field.
func (_c *ResourceSupplyLedgerCreate) SetAdminUserID(v int64) *ResourceSupplyLedgerCreate {
	_c.mutation.SetAdminUserID(v)
	return _c
}

// SetNillableAdminUserID sets the "admin_user_id" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableAdminUserID(v *int64) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetAdminUserID(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *ResourceSupplyLedgerCreate) SetNote(v string) *ResourceSupplyLedgerCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ResourceSupplyLedgerCreate) SetNillableNote(v *string) *ResourceSupplyLedgerCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// Mutation returns the ResourceSupplyLedgerMutation object of the builder.
func (_c *ResourceSupplyLedgerCreate) Mutation() *ResourceSupplyLedgerMutation {
	return _c.mutation
}

// Save creates the ResourceSupplyLedger in the database.
func (_c *ResourceSupplyLedgerCreate) Save(ctx context.Context) (*ResourceSupplyLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceSupplyLedgerCreate) SaveX(ctx context.Context) *ResourceSupplyLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceSupplyLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceSupplyLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceSupplyLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resourcesupplyledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resourcesupplyledger.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := resourcesupplyledger.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		v := resourcesupplyledger.DefaultBalanceAfter
		_c.mutation.SetBalanceAfter(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceSupplyLedgerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResourceSupplyLedger.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResourceSupplyLedger.updated_at"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "ResourceSupplyLedger.owner_user_id"`)}
	}
	if _, ok := _c.mutation.LedgerType(); !ok {
		return &ValidationError{Name: "ledger_type", err: errors.New(`ent: missing required field "ResourceSupplyLedger.ledger_type"`)}
	}
	if v, ok := _c.mutation.LedgerType(); ok {
		if err := resourcesupplyledger.LedgerTypeValidator(v); err != nil {
			return &ValidationError{Name: "ledger_type", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyLedger.ledger_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := resourcesupplyledger.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyLedger.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ResourceSupplyLedger.amount"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "ResourceSupplyLedger.balance_after"`)}
	}
	if v, ok := _c.mutation.BalanceAfter(); ok {
		if err := resourcesupplyledger.BalanceAfterValidator(v); err != nil {
			return &ValidationError{Name: "balance_after", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyLedger.balance_after": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := resourcesupplyledger.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyLedger.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := resourcesupplyledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyLedger.request_id": %w`, err)}
		}
	}
	return nil
}

func (_c *ResourceSupplyLedgerCreate) sqlSave(ctx context.Context) (*ResourceSupplyLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceSupplyLedgerCreate) createSpec() (*ResourceSupplyLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceSupplyLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resourcesupplyledger.Table, sqlgraph.NewFieldSpec(resourcesupplyledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resourcesupplyledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcesupplyledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(resourcesupplyledger.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.CallerUserID(); ok {
		_spec.SetField(resourcesupplyledger.FieldCallerUserID, field.TypeInt64, value)
		_node.CallerUserID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(resourcesupplyledger.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(resourcesupplyledger.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(resourcesupplyledger.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.UsageBillingEventID(); ok {
		_spec.SetField(resourcesupplyledger.FieldUsageBillingEventID, field.TypeInt64, value)
		_node.UsageBillingEventID = &value
	}
	if value, ok := _c.mutation.LedgerType(); ok {
		_spec.SetField(resourcesupplyledger.FieldLedgerType, field.TypeString, value)
		_node.LedgerType = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(resourcesupplyledger.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(resourcesupplyledger.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(resourcesupplyledger.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(resourcesupplyledger.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = &value
	}
	if value, ok := _c.mutation.RewardMultiplier(); ok {
		_spec.SetField(resourcesupplyledger.FieldRewardMultiplier, field.TypeFloat64, value)
		_node.RewardMultiplier = &value
	}
	if value, ok := _c.mutation.BillingType(); ok {
		_spec.SetField(resourcesupplyledger.FieldBillingType, field.TypeInt8, value)
		_node.BillingType = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(resourcesupplyledger.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(resourcesupplyledger.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.AdminUserID(); ok {
		_spec.SetField(resourcesupplyledger.FieldAdminUserID, field.TypeInt64, value)
		_node.AdminUserID = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(resourcesupplyledger.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceSupplyLedger.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceSupplyLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceSupplyLedgerCreate) OnConflict(opts ...sql.ConflictOption) *ResourceSupplyLedgerUpsertOne {
	_c.conflict = opts
	return &ResourceSupplyLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceSupplyLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceSupplyLedgerCreate) OnConflictColumns(columns ...string) *ResourceSupplyLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceSupplyLedgerUpsertOne{
		create: _c,
	}
}

type (
	// ResourceSupplyLedgerUpsertOne is the builder for "upsert"-ing
	//  one ResourceSupplyLedger node.
	ResourceSupplyLedgerUpsertOne struct {
		create *ResourceSupplyLedgerCreate
	}

	// ResourceSupplyLedgerUpsert is the "OnConflict" setter.
	ResourceSupplyLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceSupplyLedgerUpsert) SetUpdatedAt(v time.Time) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateUpdatedAt() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldUpdatedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ResourceSupplyLedgerUpsert) SetOwnerUserID(v int64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateOwnerUserID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *ResourceSupplyLedgerUpsert) AddOwnerUserID(v int64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldOwnerUserID, v)
	return u
}

// SetCallerUserID sets the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsert) SetCallerUserID(v int64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldCallerUserID, v)
	return u
}

// UpdateCallerUserID sets the "caller_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateCallerUserID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldCallerUserID)
	return u
}

// AddCallerUserID adds v to the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsert) AddCallerUserID(v int64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldCallerUserID, v)
	return u
}

// ClearCallerUserID clears the value of the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsert) ClearCallerUserID() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldCallerUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsert) SetAPIKeyID(v int64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateAPIKeyID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsert) AddAPIKeyID(v int64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsert) ClearAPIKeyID() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ResourceSupplyLedgerUpsert) SetGroupID(v int64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateGroupID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *ResourceSupplyLedgerUpsert) AddGroupID(v int64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ResourceSupplyLedgerUpsert) ClearGroupID() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ResourceSupplyLedgerUpsert) SetAccountID(v int64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateAccountID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *ResourceSupplyLedgerUpsert) AddAccountID(v int64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *ResourceSupplyLedgerUpsert) ClearAccountID() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldAccountID)
	return u
}

// SetUsageBillingEventID sets the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsert) SetUsageBillingEventID(v int64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldUsageBillingEventID, v)
	return u
}

// UpdateUsageBillingEventID sets the "usage_billing_event_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateUsageBillingEventID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldUsageBillingEventID)
	return u
}

// AddUsageBillingEventID adds v to the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsert) AddUsageBillingEventID(v int64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldUsageBillingEventID, v)
	return u
}

// ClearUsageBillingEventID clears the value of the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsert) ClearUsageBillingEventID() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldUsageBillingEventID)
	return u
}

// SetLedgerType sets the "ledger_type" field.
func (u *ResourceSupplyLedgerUpsert) SetLedgerType(v string) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldLedgerType, v)
	return u
}

// UpdateLedgerType sets the "ledger_type" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateLedgerType() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldLedgerType)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ResourceSupplyLedgerUpsert) SetIdempotencyKey(v string) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateIdempotencyKey() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ResourceSupplyLedgerUpsert) ClearIdempotencyKey() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldIdempotencyKey)
	return u
}

// SetAmount sets the "amount" field.
func (u *ResourceSupplyLedgerUpsert) SetAmount(v float64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateAmount() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ResourceSupplyLedgerUpsert) AddAmount(v float64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldAmount, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *ResourceSupplyLedgerUpsert) SetBalanceAfter(v float64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateBalanceAfter() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *ResourceSupplyLedgerUpsert) AddBalanceAfter(v float64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldBalanceAfter, v)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsert) SetActualCost(v float64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateActualCost() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsert) AddActualCost(v float64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldActualCost, v)
	return u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsert) ClearActualCost() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldActualCost)
	return u
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsert) SetRewardMultiplier(v float64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldRewardMultiplier, v)
	return u
}

// UpdateRewardMultiplier sets the "reward_multiplier" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateRewardMultiplier() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldRewardMultiplier)
	return u
}

// AddRewardMultiplier adds v to the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsert) AddRewardMultiplier(v float64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldRewardMultiplier, v)
	return u
}

// ClearRewardMultiplier clears the value of the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsert) ClearRewardMultiplier() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldRewardMultiplier)
	return u
}

// SetBillingType sets the "billing_type" field.
func (u *ResourceSupplyLedgerUpsert) SetBillingType(v int8) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldBillingType, v)
	return u
}

// UpdateBillingType sets the "billing_type" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateBillingType() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldBillingType)
	return u
}

// AddBillingType adds v to the "billing_type" field.
func (u *ResourceSupplyLedgerUpsert) AddBillingType(v int8) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldBillingType, v)
	return u
}

// ClearBillingType clears the value of the "billing_type" field.
func (u *ResourceSupplyLedgerUpsert) ClearBillingType() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldBillingType)
	return u
}

// SetModel sets the "model" field.
func (u *ResourceSupplyLedgerUpsert) SetModel(v string) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateModel() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *ResourceSupplyLedgerUpsert) ClearModel() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldModel)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *ResourceSupplyLedgerUpsert) SetRequestID(v string) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateRequestID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *ResourceSupplyLedgerUpsert) ClearRequestID() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldRequestID)
	return u
}

// SetAdminUserID sets the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsert) SetAdminUserID(v int64) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldAdminUserID, v)
	return u
}

// UpdateAdminUserID sets the "admin_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateAdminUserID() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldAdminUserID)
	return u
}

// AddAdminUserID adds v to the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsert) AddAdminUserID(v int64) *ResourceSupplyLedgerUpsert {
	u.Add(resourcesupplyledger.FieldAdminUserID, v)
	return u
}

// ClearAdminUserID clears the value of the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsert) ClearAdminUserID() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldAdminUserID)
	return u
}

// SetNote sets the "note" field.
func (u *ResourceSupplyLedgerUpsert) SetNote(v string) *ResourceSupplyLedgerUpsert {
	u.Set(resourcesupplyledger.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsert) UpdateNote() *ResourceSupplyLedgerUpsert {
	u.SetExcluded(resourcesupplyledger.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *ResourceSupplyLedgerUpsert) ClearNote() *ResourceSupplyLedgerUpsert {
	u.SetNull(resourcesupplyledger.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResourceSupplyLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceSupplyLedgerUpsertOne) UpdateNewValues() *ResourceSupplyLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resourcesupplyledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceSupplyLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceSupplyLedgerUpsertOne) Ignore() *ResourceSupplyLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceSupplyLedgerUpsertOne) DoNothing() *ResourceSupplyLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceSupplyLedgerCreate.OnConflict
// documentation for more info.
func (u *ResourceSupplyLedgerUpsertOne) Update(set func(*ResourceSupplyLedgerUpsert)) *ResourceSupplyLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceSupplyLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceSupplyLedgerUpsertOne) SetUpdatedAt(v time.Time) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateUpdatedAt() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetOwnerUserID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) AddOwnerUserID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateOwnerUserID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetCallerUserID sets the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetCallerUserID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetCallerUserID(v)
	})
}

// AddCallerUserID adds v to the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) AddCallerUserID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddCallerUserID(v)
	})
}

// UpdateCallerUserID sets the "caller_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateCallerUserID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateCallerUserID()
	})
}

// ClearCallerUserID clears the value of the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearCallerUserID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearCallerUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetAPIKeyID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsertOne) AddAPIKeyID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateAPIKeyID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearAPIKeyID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetGroupID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ResourceSupplyLedgerUpsertOne) AddGroupID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateGroupID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearGroupID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetAccountID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ResourceSupplyLedgerUpsertOne) AddAccountID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateAccountID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearAccountID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearAccountID()
	})
}

// SetUsageBillingEventID sets the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetUsageBillingEventID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetUsageBillingEventID(v)
	})
}

// AddUsageBillingEventID adds v to the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsertOne) AddUsageBillingEventID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddUsageBillingEventID(v)
	})
}

// UpdateUsageBillingEventID sets the "usage_billing_event_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateUsageBillingEventID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateUsageBillingEventID()
	})
}

// ClearUsageBillingEventID clears the value of the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearUsageBillingEventID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearUsageBillingEventID()
	})
}

// SetLedgerType sets the "ledger_type" field.
func (u *ResourceSupplyLedgerUpsertOne) SetLedgerType(v string) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetLedgerType(v)
	})
}

// UpdateLedgerType sets the "ledger_type" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateLedgerType() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateLedgerType()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ResourceSupplyLedgerUpsertOne) SetIdempotencyKey(v string) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateIdempotencyKey() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearIdempotencyKey() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetAmount sets the "amount" field.
func (u *ResourceSupplyLedgerUpsertOne) SetAmount(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ResourceSupplyLedgerUpsertOne) AddAmount(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateAmount() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *ResourceSupplyLedgerUpsertOne) SetBalanceAfter(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *ResourceSupplyLedgerUpsertOne) AddBalanceAfter(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateBalanceAfter() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsertOne) SetActualCost(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsertOne) AddActualCost(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateActualCost() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearActualCost() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearActualCost()
	})
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsertOne) SetRewardMultiplier(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetRewardMultiplier(v)
	})
}

// AddRewardMultiplier adds v to the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsertOne) AddRewardMultiplier(v float64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddRewardMultiplier(v)
	})
}

// UpdateRewardMultiplier sets the "reward_multiplier" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateRewardMultiplier() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateRewardMultiplier()
	})
}

// ClearRewardMultiplier clears the value of the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearRewardMultiplier() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearRewardMultiplier()
	})
}

// SetBillingType sets the "billing_type" field.
func (u *ResourceSupplyLedgerUpsertOne) SetBillingType(v int8) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetBillingType(v)
	})
}

// AddBillingType adds v to the "billing_type" field.
func (u *ResourceSupplyLedgerUpsertOne) AddBillingType(v int8) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddBillingType(v)
	})
}

// UpdateBillingType sets the "billing_type" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateBillingType() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateBillingType()
	})
}

// ClearBillingType clears the value of the "billing_type" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearBillingType() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearBillingType()
	})
}

// SetModel sets the "model" field.
func (u *ResourceSupplyLedgerUpsertOne) SetModel(v string) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateModel() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearModel() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearModel()
	})
}

// SetRequestID sets the "request_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetRequestID(v string) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateRequestID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearRequestID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearRequestID()
	})
}

// SetAdminUserID sets the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) SetAdminUserID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAdminUserID(v)
	})
}

// AddAdminUserID adds v to the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) AddAdminUserID(v int64) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAdminUserID(v)
	})
}

// UpdateAdminUserID sets the "admin_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateAdminUserID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAdminUserID()
	})
}

// ClearAdminUserID clears the value of the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearAdminUserID() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearAdminUserID()
	})
}

// SetNote sets the "note" field.
func (u *ResourceSupplyLedgerUpsertOne) SetNote(v string) *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertOne) UpdateNote() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ResourceSupplyLedgerUpsertOne) ClearNote() *ResourceSupplyLedgerUpsertOne {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *ResourceSupplyLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceSupplyLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceSupplyLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceSupplyLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceSupplyLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceSupplyLedgerCreateBulk is the builder for creating many ResourceSupplyLedger entities in bulk.
type ResourceSupplyLedgerCreateBulk struct {
	config
	err      error
	builders []*ResourceSupplyLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the ResourceSupplyLedger entities in the database.
func (_c *ResourceSupplyLedgerCreateBulk) Save(ctx context.Context) ([]*ResourceSupplyLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResourceSupplyLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceSupplyLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceSupplyLedgerCreateBulk) SaveX(ctx context.Context) []*ResourceSupplyLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceSupplyLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceSupplyLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceSupplyLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceSupplyLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceSupplyLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceSupplyLedgerUpsertBulk {
	_c.conflict = opts
	return &ResourceSupplyLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceSupplyLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceSupplyLedgerCreateBulk) OnConflictColumns(columns ...string) *ResourceSupplyLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceSupplyLedgerUpsertBulk{
		create: _c,
	}
}

// ResourceSupplyLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of ResourceSupplyLedger nodes.
type ResourceSupplyLedgerUpsertBulk struct {
	create *ResourceSupplyLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResourceSupplyLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceSupplyLedgerUpsertBulk) UpdateNewValues() *ResourceSupplyLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resourcesupplyledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceSupplyLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceSupplyLedgerUpsertBulk) Ignore() *ResourceSupplyLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceSupplyLedgerUpsertBulk) DoNothing() *ResourceSupplyLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceSupplyLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceSupplyLedgerUpsertBulk) Update(set func(*ResourceSupplyLedgerUpsert)) *ResourceSupplyLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceSupplyLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetUpdatedAt(v time.Time) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateUpdatedAt() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetOwnerUserID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddOwnerUserID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateOwnerUserID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetCallerUserID sets the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetCallerUserID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetCallerUserID(v)
	})
}

// AddCallerUserID adds v to the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddCallerUserID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddCallerUserID(v)
	})
}

// UpdateCallerUserID sets the "caller_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateCallerUserID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateCallerUserID()
	})
}

// ClearCallerUserID clears the value of the "caller_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearCallerUserID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearCallerUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetAPIKeyID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddAPIKeyID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateAPIKeyID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearAPIKeyID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetGroupID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddGroupID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateGroupID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearGroupID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetAccountID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddAccountID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateAccountID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearAccountID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearAccountID()
	})
}

// SetUsageBillingEventID sets the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetUsageBillingEventID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetUsageBillingEventID(v)
	})
}

// AddUsageBillingEventID adds v to the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddUsageBillingEventID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddUsageBillingEventID(v)
	})
}

// UpdateUsageBillingEventID sets the "usage_billing_event_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateUsageBillingEventID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateUsageBillingEventID()
	})
}

// ClearUsageBillingEventID clears the value of the "usage_billing_event_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearUsageBillingEventID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearUsageBillingEventID()
	})
}

// SetLedgerType sets the "ledger_type" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetLedgerType(v string) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetLedgerType(v)
	})
}

// UpdateLedgerType sets the "ledger_type" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateLedgerType() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateLedgerType()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetIdempotencyKey(v string) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateIdempotencyKey() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearIdempotencyKey() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetAmount sets the "amount" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetAmount(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddAmount(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateAmount() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetBalanceAfter(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddBalanceAfter(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateBalanceAfter() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetActualCost(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddActualCost(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateActualCost() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearActualCost() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearActualCost()
	})
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetRewardMultiplier(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetRewardMultiplier(v)
	})
}

// AddRewardMultiplier adds v to the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddRewardMultiplier(v float64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddRewardMultiplier(v)
	})
}

// UpdateRewardMultiplier sets the "reward_multiplier" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateRewardMultiplier() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateRewardMultiplier()
	})
}

// ClearRewardMultiplier clears the value of the "reward_multiplier" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearRewardMultiplier() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearRewardMultiplier()
	})
}

// SetBillingType sets the "billing_type" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetBillingType(v int8) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetBillingType(v)
	})
}

// AddBillingType adds v to the "billing_type" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddBillingType(v int8) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddBillingType(v)
	})
}

// UpdateBillingType sets the "billing_type" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateBillingType() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateBillingType()
	})
}

// ClearBillingType clears the value of the "billing_type" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearBillingType() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearBillingType()
	})
}

// SetModel sets the "model" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetModel(v string) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateModel() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearModel() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearModel()
	})
}

// SetRequestID sets the "request_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetRequestID(v string) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateRequestID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearRequestID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearRequestID()
	})
}

// SetAdminUserID sets the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetAdminUserID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetAdminUserID(v)
	})
}

// AddAdminUserID adds v to the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) AddAdminUserID(v int64) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.AddAdminUserID(v)
	})
}

// UpdateAdminUserID sets the "admin_user_id" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateAdminUserID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateAdminUserID()
	})
}

// ClearAdminUserID clears the value of the "admin_user_id" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearAdminUserID() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearAdminUserID()
	})
}

// SetNote sets the "note" field.
func (u *ResourceSupplyLedgerUpsertBulk) SetNote(v string) *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ResourceSupplyLedgerUpsertBulk) UpdateNote() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ResourceSupplyLedgerUpsertBulk) ClearNote() *ResourceSupplyLedgerUpsertBulk {
	return u.Update(func(s *ResourceSupplyLedgerUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *ResourceSupplyLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceSupplyLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceSupplyLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceSupplyLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
