// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resourcesupplybalance"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResourceSupplyBalanceUpdate is the builder for updating ResourceSupplyBalance entities.
type ResourceSupplyBalanceUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceSupplyBalanceMutation
}

// Where appends a list predicates to the ResourceSupplyBalanceUpdate builder.
func (_u *ResourceSupplyBalanceUpdate) Where(ps ...predicate.ResourceSupplyBalance) *ResourceSupplyBalanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceSupplyBalanceUpdate) SetUpdatedAt(v time.Time) *ResourceSupplyBalanceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResourceSupplyBalanceUpdate) SetUserID(v int64) *ResourceSupplyBalanceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdate) SetNillableUserID(v *int64) *ResourceSupplyBalanceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAvailableAmount sets the "available_amount" field.
func (_u *ResourceSupplyBalanceUpdate) SetAvailableAmount(v float64) *ResourceSupplyBalanceUpdate {
	_u.mutation.ResetAvailableAmount()
	_u.mutation.SetAvailableAmount(v)
	return _u
}

// SetNillableAvailableAmount sets the "available_amount" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdate) SetNillableAvailableAmount(v *float64) *ResourceSupplyBalanceUpdate {
	if v != nil {
		_u.SetAvailableAmount(*v)
	}
	return _u
}

// AddAvailableAmount adds value to the "available_amount" field.
func (_u *ResourceSupplyBalanceUpdate) AddAvailableAmount(v float64) *ResourceSupplyBalanceUpdate {
	_u.mutation.AddAvailableAmount(v)
	return _u
}

// SetLifetimeEarnedAmount sets the "lifetime_earned_amount" field.
func (_u *ResourceSupplyBalanceUpdate) SetLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpdate {
	_u.mutation.ResetLifetimeEarnedAmount()
	_u.mutation.SetLifetimeEarnedAmount(v)
	return _u
}

// SetNillableLifetimeEarnedAmount sets the "lifetime_earned_amount" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdate) SetNillableLifetimeEarnedAmount(v *float64) *ResourceSupplyBalanceUpdate {
	if v != nil {
		_u.SetLifetimeEarnedAmount(*v)
	}
	return _u
}

// AddLifetimeEarnedAmount adds value to the "lifetime_earned_amount" field.
func (_u *ResourceSupplyBalanceUpdate) AddLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpdate {
	_u.mutation.AddLifetimeEarnedAmount(v)
	return _u
}

// SetLifetimeTransferredAmount sets the "lifetime_transferred_amount" field.
func (_u *ResourceSupplyBalanceUpdate) SetLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpdate {
	_u.mutation.ResetLifetimeTransferredAmount()
	_u.mutation.SetLifetimeTransferredAmount(v)
	return _u
}

// SetNillableLifetimeTransferredAmount sets the "lifetime_transferred_amount" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdate) SetNillableLifetimeTransferredAmount(v *float64) *ResourceSupplyBalanceUpdate {
	if v != nil {
		_u.SetLifetimeTransferredAmount(*v)
	}
	return _u
}

// AddLifetimeTransferredAmount adds value to the "lifetime_transferred_amount" field.
func (_u *ResourceSupplyBalanceUpdate) AddLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpdate {
	_u.mutation.AddLifetimeTransferredAmount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ResourceSupplyBalanceUpdate) SetUser(v *User) *ResourceSupplyBalanceUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ResourceSupplyBalanceMutation object of the builder.
func (_u *ResourceSupplyBalanceUpdate) Mutation() *ResourceSupplyBalanceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ResourceSupplyBalanceUpdate) ClearUser() *ResourceSupplyBalanceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceSupplyBalanceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceSupplyBalanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceSupplyBalanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceSupplyBalanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceSupplyBalanceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourcesupplybalance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceSupplyBalanceUpdate) check() error {
	if v, ok := _u.mutation.AvailableAmount(); ok {
		if err := resourcesupplybalance.AvailableAmountValidator(v); err != nil {
			return &ValidationError{Name: "available_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.available_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeEarnedAmount(); ok {
		if err := resourcesupplybalance.LifetimeEarnedAmountValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_earned_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.lifetime_earned_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeTransferredAmount(); ok {
		if err := resourcesupplybalance.LifetimeTransferredAmountValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_transferred_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.lifetime_transferred_amount": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResourceSupplyBalance.user"`)
	}
	return nil
}

func (_u *ResourceSupplyBalanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcesupplybalance.Table, resourcesupplybalance.Columns, sqlgraph.NewFieldSpec(resourcesupplybalance.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcesupplybalance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AvailableAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvailableAmount(); ok {
		_spec.AddField(resourcesupplybalance.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LifetimeEarnedAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldLifetimeEarnedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeEarnedAmount(); ok {
		_spec.AddField(resourcesupplybalance.FieldLifetimeEarnedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LifetimeTransferredAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldLifetimeTransferredAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeTransferredAmount(); ok {
		_spec.AddField(resourcesupplybalance.FieldLifetimeTransferredAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcesupplybalance.UserTable,
			Columns: []string{resourcesupplybalance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcesupplybalance.UserTable,
			Columns: []string{resourcesupplybalance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcesupplybalance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceSupplyBalanceUpdateOne is the builder for updating a single ResourceSupplyBalance entity.
type ResourceSupplyBalanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceSupplyBalanceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceSupplyBalanceUpdateOne) SetUpdatedAt(v time.Time) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResourceSupplyBalanceUpdateOne) SetUserID(v int64) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdateOne) SetNillableUserID(v *int64) *ResourceSupplyBalanceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAvailableAmount sets the "available_amount" field.
func (_u *ResourceSupplyBalanceUpdateOne) SetAvailableAmount(v float64) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.ResetAvailableAmount()
	_u.mutation.SetAvailableAmount(v)
	return _u
}

// SetNillableAvailableAmount sets the "available_amount" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdateOne) SetNillableAvailableAmount(v *float64) *ResourceSupplyBalanceUpdateOne {
	if v != nil {
		_u.SetAvailableAmount(*v)
	}
	return _u
}

// AddAvailableAmount adds value to the "available_amount" field.
func (_u *ResourceSupplyBalanceUpdateOne) AddAvailableAmount(v float64) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.AddAvailableAmount(v)
	return _u
}

// SetLifetimeEarnedAmount sets the "lifetime_earned_amount" field.
func (_u *ResourceSupplyBalanceUpdateOne) SetLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.ResetLifetimeEarnedAmount()
	_u.mutation.SetLifetimeEarnedAmount(v)
	return _u
}

// SetNillableLifetimeEarnedAmount sets the "lifetime_earned_amount" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdateOne) SetNillableLifetimeEarnedAmount(v *float64) *ResourceSupplyBalanceUpdateOne {
	if v != nil {
		_u.SetLifetimeEarnedAmount(*v)
	}
	return _u
}

// AddLifetimeEarnedAmount adds value to the "lifetime_earned_amount" field.
func (_u *ResourceSupplyBalanceUpdateOne) AddLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.AddLifetimeEarnedAmount(v)
	return _u
}

// SetLifetimeTransferredAmount sets the "lifetime_transferred_amount" field.
func (_u *ResourceSupplyBalanceUpdateOne) SetLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.ResetLifetimeTransferredAmount()
	_u.mutation.SetLifetimeTransferredAmount(v)
	return _u
}

// SetNillableLifetimeTransferredAmount sets the "lifetime_transferred_amount" field if the given value is not nil.
func (_u *ResourceSupplyBalanceUpdateOne) SetNillableLifetimeTransferredAmount(v *float64) *ResourceSupplyBalanceUpdateOne {
	if v != nil {
		_u.SetLifetimeTransferredAmount(*v)
	}
	return _u
}

// AddLifetimeTransferredAmount adds value to the "lifetime_transferred_amount" field.
func (_u *ResourceSupplyBalanceUpdateOne) AddLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.AddLifetimeTransferredAmount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ResourceSupplyBalanceUpdateOne) SetUser(v *User) *ResourceSupplyBalanceUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ResourceSupplyBalanceMutation object of the builder.
func (_u *ResourceSupplyBalanceUpdateOne) Mutation() *ResourceSupplyBalanceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ResourceSupplyBalanceUpdateOne) ClearUser() *ResourceSupplyBalanceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ResourceSupplyBalanceUpdate builder.
func (_u *ResourceSupplyBalanceUpdateOne) Where(ps ...predicate.ResourceSupplyBalance) *ResourceSupplyBalanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceSupplyBalanceUpdateOne) Select(field string, fields ...string) *ResourceSupplyBalanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResourceSupplyBalance entity.
func (_u *ResourceSupplyBalanceUpdateOne) Save(ctx context.Context) (*ResourceSupplyBalance, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceSupplyBalanceUpdateOne) SaveX(ctx context.Context) *ResourceSupplyBalance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceSupplyBalanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceSupplyBalanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceSupplyBalanceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourcesupplybalance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceSupplyBalanceUpdateOne) check() error {
	if v, ok := _u.mutation.AvailableAmount(); ok {
		if err := resourcesupplybalance.AvailableAmountValidator(v); err != nil {
			return &ValidationError{Name: "available_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.available_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeEarnedAmount(); ok {
		if err := resourcesupplybalance.LifetimeEarnedAmountValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_earned_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.lifetime_earned_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeTransferredAmount(); ok {
		if err := resourcesupplybalance.LifetimeTransferredAmountValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_transferred_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.lifetime_transferred_amount": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResourceSupplyBalance.user"`)
	}
	return nil
}

func (_u *ResourceSupplyBalanceUpdateOne) sqlSave(ctx context.Context) (_node *ResourceSupplyBalance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcesupplybalance.Table, resourcesupplybalance.Columns, sqlgraph.NewFieldSpec(resourcesupplybalance.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceSupplyBalance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourcesupplybalance.FieldID)
		for _, f := range fields {
			if !resourcesupplybalance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourcesupplybalance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcesupplybalance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AvailableAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvailableAmount(); ok {
		_spec.AddField(resourcesupplybalance.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LifetimeEarnedAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldLifetimeEarnedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeEarnedAmount(); ok {
		_spec.AddField(resourcesupplybalance.FieldLifetimeEarnedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LifetimeTransferredAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldLifetimeTransferredAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeTransferredAmount(); ok {
		_spec.AddField(resourcesupplybalance.FieldLifetimeTransferredAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcesupplybalance.UserTable,
			Columns: []string{resourcesupplybalance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcesupplybalance.UserTable,
			Columns: []string{resourcesupplybalance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ResourceSupplyBalance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcesupplybalance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
