// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resourcesupplybalance"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResourceSupplyBalanceCreate is the builder for creating a ResourceSupplyBalance entity.
type ResourceSupplyBalanceCreate struct {
	config
	mutation *ResourceSupplyBalanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceSupplyBalanceCreate) SetCreatedAt(v time.Time) *ResourceSupplyBalanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceSupplyBalanceCreate) SetNillableCreatedAt(v *time.Time) *ResourceSupplyBalanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceSupplyBalanceCreate) SetUpdatedAt(v time.Time) *ResourceSupplyBalanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceSupplyBalanceCreate) SetNillableUpdatedAt(v *time.Time) *ResourceSupplyBalanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ResourceSupplyBalanceCreate) SetUserID(v int64) *ResourceSupplyBalanceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAvailableAmount sets the "available_amount" field.
func (_c *ResourceSupplyBalanceCreate) SetAvailableAmount(v float64) *ResourceSupplyBalanceCreate {
	_c.mutation.SetAvailableAmount(v)
	return _c
}

// SetNillableAvailableAmount sets the "available_amount" field if the given value is not nil.
func (_c *ResourceSupplyBalanceCreate) SetNillableAvailableAmount(v *float64) *ResourceSupplyBalanceCreate {
	if v != nil {
		_c.SetAvailableAmount(*v)
	}
	return _c
}

// SetLifetimeEarnedAmount sets the "lifetime_earned_amount" field.
func (_c *ResourceSupplyBalanceCreate) SetLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceCreate {
	_c.mutation.SetLifetimeEarnedAmount(v)
	return _c
}

// SetNillableLifetimeEarnedAmount sets the "lifetime_earned_amount" field if the given value is not nil.
func (_c *ResourceSupplyBalanceCreate) SetNillableLifetimeEarnedAmount(v *float64) *ResourceSupplyBalanceCreate {
	if v != nil {
		_c.SetLifetimeEarnedAmount(*v)
	}
	return _c
}

// SetLifetimeTransferredAmount sets the "lifetime_transferred_amount" field.
func (_c *ResourceSupplyBalanceCreate) SetLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceCreate {
	_c.mutation.SetLifetimeTransferredAmount(v)
	return _c
}

// SetNillableLifetimeTransferredAmount sets the "lifetime_transferred_amount" field if the given value is not nil.
func (_c *ResourceSupplyBalanceCreate) SetNillableLifetimeTransferredAmount(v *float64) *ResourceSupplyBalanceCreate {
	if v != nil {
		_c.SetLifetimeTransferredAmount(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ResourceSupplyBalanceCreate) SetUser(v *User) *ResourceSupplyBalanceCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ResourceSupplyBalanceMutation object of the builder.
func (_c *ResourceSupplyBalanceCreate) Mutation() *ResourceSupplyBalanceMutation {
	return _c.mutation
}

// Save creates the ResourceSupplyBalance in the database.
func (_c *ResourceSupplyBalanceCreate) Save(ctx context.Context) (*ResourceSupplyBalance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceSupplyBalanceCreate) SaveX(ctx context.Context) *ResourceSupplyBalance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceSupplyBalanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceSupplyBalanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceSupplyBalanceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resourcesupplybalance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resourcesupplybalance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AvailableAmount(); !ok {
		v := resourcesupplybalance.DefaultAvailableAmount
		_c.mutation.SetAvailableAmount(v)
	}
	if _, ok := _c.mutation.LifetimeEarnedAmount(); !ok {
		v := resourcesupplybalance.DefaultLifetimeEarnedAmount
		_c.mutation.SetLifetimeEarnedAmount(v)
	}
	if _, ok := _c.mutation.LifetimeTransferredAmount(); !ok {
		v := resourcesupplybalance.DefaultLifetimeTransferredAmount
		_c.mutation.SetLifetimeTransferredAmount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceSupplyBalanceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResourceSupplyBalance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResourceSupplyBalance.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ResourceSupplyBalance.user_id"`)}
	}
	if _, ok := _c.mutation.AvailableAmount(); !ok {
		return &ValidationError{Name: "available_amount", err: errors.New(`ent: missing required field "ResourceSupplyBalance.available_amount"`)}
	}
	if v, ok := _c.mutation.AvailableAmount(); ok {
		if err := resourcesupplybalance.AvailableAmountValidator(v); err != nil {
			return &ValidationError{Name: "available_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.available_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LifetimeEarnedAmount(); !ok {
		return &ValidationError{Name: "lifetime_earned_amount", err: errors.New(`ent: missing required field "ResourceSupplyBalance.lifetime_earned_amount"`)}
	}
	if v, ok := _c.mutation.LifetimeEarnedAmount(); ok {
		if err := resourcesupplybalance.LifetimeEarnedAmountValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_earned_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.lifetime_earned_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LifetimeTransferredAmount(); !ok {
		return &ValidationError{Name: "lifetime_transferred_amount", err: errors.New(`ent: missing required field "ResourceSupplyBalance.lifetime_transferred_amount"`)}
	}
	if v, ok := _c.mutation.LifetimeTransferredAmount(); ok {
		if err := resourcesupplybalance.LifetimeTransferredAmountValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_transferred_amount", err: fmt.Errorf(`ent: validator failed for field "ResourceSupplyBalance.lifetime_transferred_amount": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ResourceSupplyBalance.user"`)}
	}
	return nil
}

func (_c *ResourceSupplyBalanceCreate) sqlSave(ctx context.Context) (*ResourceSupplyBalance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceSupplyBalanceCreate) createSpec() (*ResourceSupplyBalance, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceSupplyBalance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resourcesupplybalance.Table, sqlgraph.NewFieldSpec(resourcesupplybalance.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resourcesupplybalance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resourcesupplybalance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AvailableAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldAvailableAmount, field.TypeFloat64, value)
		_node.AvailableAmount = value
	}
	if value, ok := _c.mutation.LifetimeEarnedAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldLifetimeEarnedAmount, field.TypeFloat64, value)
		_node.LifetimeEarnedAmount = value
	}
	if value, ok := _c.mutation.LifetimeTransferredAmount(); ok {
		_spec.SetField(resourcesupplybalance.FieldLifetimeTransferredAmount, field.TypeFloat64, value)
		_node.LifetimeTransferredAmount = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcesupplybalance.UserTable,
			Columns: []string{resourcesupplybalance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceSupplyBalance.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceSupplyBalanceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceSupplyBalanceCreate) OnConflict(opts ...sql.ConflictOption) *ResourceSupplyBalanceUpsertOne {
	_c.conflict = opts
	return &ResourceSupplyBalanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceSupplyBalance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceSupplyBalanceCreate) OnConflictColumns(columns ...string) *ResourceSupplyBalanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceSupplyBalanceUpsertOne{
		create: _c,
	}
}

type (
	// ResourceSupplyBalanceUpsertOne is the builder for "upsert"-ing
	//  one ResourceSupplyBalance node.
	ResourceSupplyBalanceUpsertOne struct {
		create *ResourceSupplyBalanceCreate
	}

	// ResourceSupplyBalanceUpsert is the "OnConflict" setter.
	ResourceSupplyBalanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceSupplyBalanceUpsert) SetUpdatedAt(v time.Time) *ResourceSupplyBalanceUpsert {
	u.Set(resourcesupplybalance.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsert) UpdateUpdatedAt() *ResourceSupplyBalanceUpsert {
	u.SetExcluded(resourcesupplybalance.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ResourceSupplyBalanceUpsert) SetUserID(v int64) *ResourceSupplyBalanceUpsert {
	u.Set(resourcesupplybalance.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsert) UpdateUserID() *ResourceSupplyBalanceUpsert {
	u.SetExcluded(resourcesupplybalance.FieldUserID)
	return u
}

// SetAvailableAmount sets the "available_amount" field.
func (u *ResourceSupplyBalanceUpsert) SetAvailableAmount(v float64) *ResourceSupplyBalanceUpsert {
	u.Set(resourcesupplybalance.FieldAvailableAmount, v)
	return u
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsert) UpdateAvailableAmount() *ResourceSupplyBalanceUpsert {
	u.SetExcluded(resourcesupplybalance.FieldAvailableAmount)
	return u
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *ResourceSupplyBalanceUpsert) AddAvailableAmount(v float64) *ResourceSupplyBalanceUpsert {
	u.Add(resourcesupplybalance.FieldAvailableAmount, v)
	return u
}

// SetLifetimeEarnedAmount sets the "lifetime_earned_amount" field.
func (u *ResourceSupplyBalanceUpsert) SetLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpsert {
	u.Set(resourcesupplybalance.FieldLifetimeEarnedAmount, v)
	return u
}

// UpdateLifetimeEarnedAmount sets the "lifetime_earned_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsert) UpdateLifetimeEarnedAmount() *ResourceSupplyBalanceUpsert {
	u.SetExcluded(resourcesupplybalance.FieldLifetimeEarnedAmount)
	return u
}

// AddLifetimeEarnedAmount adds v to the "lifetime_earned_amount" field.
func (u *ResourceSupplyBalanceUpsert) AddLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpsert {
	u.Add(resourcesupplybalance.FieldLifetimeEarnedAmount, v)
	return u
}

// SetLifetimeTransferredAmount sets the "lifetime_transferred_amount" field.
func (u *ResourceSupplyBalanceUpsert) SetLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpsert {
	u.Set(resourcesupplybalance.FieldLifetimeTransferredAmount, v)
	return u
}

// UpdateLifetimeTransferredAmount sets the "lifetime_transferred_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsert) UpdateLifetimeTransferredAmount() *ResourceSupplyBalanceUpsert {
	u.SetExcluded(resourcesupplybalance.FieldLifetimeTransferredAmount)
	return u
}

// AddLifetimeTransferredAmount adds v to the "lifetime_transferred_amount" field.
func (u *ResourceSupplyBalanceUpsert) AddLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpsert {
	u.Add(resourcesupplybalance.FieldLifetimeTransferredAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResourceSupplyBalance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceSupplyBalanceUpsertOne) UpdateNewValues() *ResourceSupplyBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resourcesupplybalance.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceSupplyBalance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceSupplyBalanceUpsertOne) Ignore() *ResourceSupplyBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceSupplyBalanceUpsertOne) DoNothing() *ResourceSupplyBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceSupplyBalanceCreate.OnConflict
// documentation for more info.
func (u *ResourceSupplyBalanceUpsertOne) Update(set func(*ResourceSupplyBalanceUpsert)) *ResourceSupplyBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceSupplyBalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceSupplyBalanceUpsertOne) SetUpdatedAt(v time.Time) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertOne) UpdateUpdatedAt() *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResourceSupplyBalanceUpsertOne) SetUserID(v int64) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertOne) UpdateUserID() *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateUserID()
	})
}

// SetAvailableAmount sets the "available_amount" field.
func (u *ResourceSupplyBalanceUpsertOne) SetAvailableAmount(v float64) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetAvailableAmount(v)
	})
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *ResourceSupplyBalanceUpsertOne) AddAvailableAmount(v float64) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.AddAvailableAmount(v)
	})
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertOne) UpdateAvailableAmount() *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateAvailableAmount()
	})
}

// SetLifetimeEarnedAmount sets the "lifetime_earned_amount" field.
func (u *ResourceSupplyBalanceUpsertOne) SetLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetLifetimeEarnedAmount(v)
	})
}

// AddLifetimeEarnedAmount adds v to the "lifetime_earned_amount" field.
func (u *ResourceSupplyBalanceUpsertOne) AddLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.AddLifetimeEarnedAmount(v)
	})
}

// UpdateLifetimeEarnedAmount sets the "lifetime_earned_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertOne) UpdateLifetimeEarnedAmount() *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateLifetimeEarnedAmount()
	})
}

// SetLifetimeTransferredAmount sets the "lifetime_transferred_amount" field.
func (u *ResourceSupplyBalanceUpsertOne) SetLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetLifetimeTransferredAmount(v)
	})
}

// AddLifetimeTransferredAmount adds v to the "lifetime_transferred_amount" field.
func (u *ResourceSupplyBalanceUpsertOne) AddLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.AddLifetimeTransferredAmount(v)
	})
}

// UpdateLifetimeTransferredAmount sets the "lifetime_transferred_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertOne) UpdateLifetimeTransferredAmount() *ResourceSupplyBalanceUpsertOne {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateLifetimeTransferredAmount()
	})
}

// Exec executes the query.
func (u *ResourceSupplyBalanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceSupplyBalanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceSupplyBalanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceSupplyBalanceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceSupplyBalanceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceSupplyBalanceCreateBulk is the builder for creating many ResourceSupplyBalance entities in bulk.
type ResourceSupplyBalanceCreateBulk struct {
	config
	err      error
	builders []*ResourceSupplyBalanceCreate
	conflict []sql.ConflictOption
}

// Save creates the ResourceSupplyBalance entities in the database.
func (_c *ResourceSupplyBalanceCreateBulk) Save(ctx context.Context) ([]*ResourceSupplyBalance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResourceSupplyBalance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceSupplyBalanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceSupplyBalanceCreateBulk) SaveX(ctx context.Context) []*ResourceSupplyBalance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceSupplyBalanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceSupplyBalanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceSupplyBalance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceSupplyBalanceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceSupplyBalanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceSupplyBalanceUpsertBulk {
	_c.conflict = opts
	return &ResourceSupplyBalanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceSupplyBalance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceSupplyBalanceCreateBulk) OnConflictColumns(columns ...string) *ResourceSupplyBalanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceSupplyBalanceUpsertBulk{
		create: _c,
	}
}

// ResourceSupplyBalanceUpsertBulk is the builder for "upsert"-ing
// a bulk of ResourceSupplyBalance nodes.
type ResourceSupplyBalanceUpsertBulk struct {
	create *ResourceSupplyBalanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResourceSupplyBalance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceSupplyBalanceUpsertBulk) UpdateNewValues() *ResourceSupplyBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resourcesupplybalance.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceSupplyBalance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceSupplyBalanceUpsertBulk) Ignore() *ResourceSupplyBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceSupplyBalanceUpsertBulk) DoNothing() *ResourceSupplyBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceSupplyBalanceCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceSupplyBalanceUpsertBulk) Update(set func(*ResourceSupplyBalanceUpsert)) *ResourceSupplyBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceSupplyBalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceSupplyBalanceUpsertBulk) SetUpdatedAt(v time.Time) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertBulk) UpdateUpdatedAt() *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResourceSupplyBalanceUpsertBulk) SetUserID(v int64) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertBulk) UpdateUserID() *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateUserID()
	})
}

// SetAvailableAmount sets the "available_amount" field.
func (u *ResourceSupplyBalanceUpsertBulk) SetAvailableAmount(v float64) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetAvailableAmount(v)
	})
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *ResourceSupplyBalanceUpsertBulk) AddAvailableAmount(v float64) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.AddAvailableAmount(v)
	})
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertBulk) UpdateAvailableAmount() *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateAvailableAmount()
	})
}

// SetLifetimeEarnedAmount sets the "lifetime_earned_amount" field.
func (u *ResourceSupplyBalanceUpsertBulk) SetLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetLifetimeEarnedAmount(v)
	})
}

// AddLifetimeEarnedAmount adds v to the "lifetime_earned_amount" field.
func (u *ResourceSupplyBalanceUpsertBulk) AddLifetimeEarnedAmount(v float64) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.AddLifetimeEarnedAmount(v)
	})
}

// UpdateLifetimeEarnedAmount sets the "lifetime_earned_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertBulk) UpdateLifetimeEarnedAmount() *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateLifetimeEarnedAmount()
	})
}

// SetLifetimeTransferredAmount sets the "lifetime_transferred_amount" field.
func (u *ResourceSupplyBalanceUpsertBulk) SetLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.SetLifetimeTransferredAmount(v)
	})
}

// AddLifetimeTransferredAmount adds v to the "lifetime_transferred_amount" field.
func (u *ResourceSupplyBalanceUpsertBulk) AddLifetimeTransferredAmount(v float64) *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.AddLifetimeTransferredAmount(v)
	})
}

// UpdateLifetimeTransferredAmount sets the "lifetime_transferred_amount" field to the value that was provided on create.
func (u *ResourceSupplyBalanceUpsertBulk) UpdateLifetimeTransferredAmount() *ResourceSupplyBalanceUpsertBulk {
	return u.Update(func(s *ResourceSupplyBalanceUpsert) {
		s.UpdateLifetimeTransferredAmount()
	})
}

// Exec executes the query.
func (u *ResourceSupplyBalanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceSupplyBalanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceSupplyBalanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceSupplyBalanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
