// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagebillingevent"
)

// UsageBillingEvent is the model entity for the UsageBillingEvent schema.
type UsageBillingEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint string `json:"request_fingerprint,omitempty"`
	// RequestPayloadHash holds the value of the "request_payload_hash" field.
	RequestPayloadHash *string `json:"request_payload_hash,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// AccountType holds the value of the "account_type" field.
	AccountType *string `json:"account_type,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// ServiceTier holds the value of the "service_tier" field.
	ServiceTier string `json:"service_tier,omitempty"`
	// ReasoningEffort holds the value of the "reasoning_effort" field.
	ReasoningEffort string `json:"reasoning_effort,omitempty"`
	// BillingType holds the value of the "billing_type" field.
	BillingType int8 `json:"billing_type,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// CacheCreationTokens holds the value of the "cache_creation_tokens" field.
	CacheCreationTokens int `json:"cache_creation_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	// CacheCreation5mTokens holds the value of the "cache_creation_5m_tokens" field.
	CacheCreation5mTokens int `json:"cache_creation_5m_tokens,omitempty"`
	// CacheCreation1hTokens holds the value of the "cache_creation_1h_tokens" field.
	CacheCreation1hTokens int `json:"cache_creation_1h_tokens,omitempty"`
	// TotalCost holds the value of the "total_cost" field.
	TotalCost float64 `json:"total_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// BalanceCost holds the value of the "balance_cost" field.
	BalanceCost float64 `json:"balance_cost,omitempty"`
	// SubscriptionCost holds the value of the "subscription_cost" field.
	SubscriptionCost float64 `json:"subscription_cost,omitempty"`
	// APIKeyQuotaCost holds the value of the "api_key_quota_cost" field.
	APIKeyQuotaCost float64 `json:"api_key_quota_cost,omitempty"`
	// APIKeyRateLimitCost holds the value of the "api_key_rate_limit_cost" field.
	APIKeyRateLimitCost float64 `json:"api_key_rate_limit_cost,omitempty"`
	// AccountQuotaCost holds the value of the "account_quota_cost" field.
	AccountQuotaCost float64 `json:"account_quota_cost,omitempty"`
	// SupplyRewardEligible holds the value of the "supply_reward_eligible" field.
	SupplyRewardEligible bool `json:"supply_reward_eligible,omitempty"`
	// SupplyOwnerUserID holds the value of the "supply_owner_user_id" field.
	SupplyOwnerUserID *int64 `json:"supply_owner_user_id,omitempty"`
	// SupplyRewardMultiplier holds the value of the "supply_reward_multiplier" field.
	SupplyRewardMultiplier float64 `json:"supply_reward_multiplier,omitempty"`
	// SupplyAccountStatus holds the value of the "supply_account_status" field.
	SupplyAccountStatus string `json:"supply_account_status,omitempty"`
	// SupplySource holds the value of the "supply_source" field.
	SupplySource string `json:"supply_source,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageBillingEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagebillingevent.FieldSupplyRewardEligible:
			values[i] = new(sql.NullBool)
		case usagebillingevent.FieldTotalCost, usagebillingevent.FieldActualCost, usagebillingevent.FieldBalanceCost, usagebillingevent.FieldSubscriptionCost, usagebillingevent.FieldAPIKeyQuotaCost, usagebillingevent.FieldAPIKeyRateLimitCost, usagebillingevent.FieldAccountQuotaCost, usagebillingevent.FieldSupplyRewardMultiplier:
			values[i] = new(sql.NullFloat64)
		case usagebillingevent.FieldID, usagebillingevent.FieldAPIKeyID, usagebillingevent.FieldUserID, usagebillingevent.FieldGroupID, usagebillingevent.FieldAccountID, usagebillingevent.FieldBillingType, usagebillingevent.FieldInputTokens, usagebillingevent.FieldOutputTokens, usagebillingevent.FieldCacheCreationTokens, usagebillingevent.FieldCacheReadTokens, usagebillingevent.FieldCacheCreation5mTokens, usagebillingevent.FieldCacheCreation1hTokens, usagebillingevent.FieldSupplyOwnerUserID:
			values[i] = new(sql.NullInt64)
		case usagebillingevent.FieldRequestID, usagebillingevent.FieldRequestFingerprint, usagebillingevent.FieldRequestPayloadHash, usagebillingevent.FieldAccountType, usagebillingevent.FieldModel, usagebillingevent.FieldServiceTier, usagebillingevent.FieldReasoningEffort, usagebillingevent.FieldSupplyAccountStatus, usagebillingevent.FieldSupplySource:
			values[i] = new(sql.NullString)
		case usagebillingevent.FieldCreatedAt, usagebillingevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageBillingEvent fields.
func (_m *UsageBillingEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagebillingevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagebillingevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagebillingevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usagebillingevent.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case usagebillingevent.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case usagebillingevent.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = value.String
			}
		case usagebillingevent.FieldRequestPayloadHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload_hash", values[i])
			} else if value.Valid {
				_m.RequestPayloadHash = new(string)
				*_m.RequestPayloadHash = value.String
			}
		case usagebillingevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usagebillingevent.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case usagebillingevent.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case usagebillingevent.FieldAccountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_type", values[i])
			} else if value.Valid {
				_m.AccountType = new(string)
				*_m.AccountType = value.String
			}
		case usagebillingevent.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case usagebillingevent.FieldServiceTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_tier", values[i])
			} else if value.Valid {
				_m.ServiceTier = value.String
			}
		case usagebillingevent.FieldReasoningEffort:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_effort", values[i])
			} else if value.Valid {
				_m.ReasoningEffort = value.String
			}
		case usagebillingevent.FieldBillingType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_type", values[i])
			} else if value.Valid {
				_m.BillingType = int8(value.Int64)
			}
		case usagebillingevent.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case usagebillingevent.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case usagebillingevent.FieldCacheCreationTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationTokens = int(value.Int64)
			}
		case usagebillingevent.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = int(value.Int64)
			}
		case usagebillingevent.FieldCacheCreation5mTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_5m_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation5mTokens = int(value.Int64)
			}
		case usagebillingevent.FieldCacheCreation1hTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_1h_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation1hTokens = int(value.Int64)
			}
		case usagebillingevent.FieldTotalCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost", values[i])
			} else if value.Valid {
				_m.TotalCost = value.Float64
			}
		case usagebillingevent.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case usagebillingevent.FieldBalanceCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_cost", values[i])
			} else if value.Valid {
				_m.BalanceCost = value.Float64
			}
		case usagebillingevent.FieldSubscriptionCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_cost", values[i])
			} else if value.Valid {
				_m.SubscriptionCost = value.Float64
			}
		case usagebillingevent.FieldAPIKeyQuotaCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_quota_cost", values[i])
			} else if value.Valid {
				_m.APIKeyQuotaCost = value.Float64
			}
		case usagebillingevent.FieldAPIKeyRateLimitCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_rate_limit_cost", values[i])
			} else if value.Valid {
				_m.APIKeyRateLimitCost = value.Float64
			}
		case usagebillingevent.FieldAccountQuotaCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field account_quota_cost", values[i])
			} else if value.Valid {
				_m.AccountQuotaCost = value.Float64
			}
		case usagebillingevent.FieldSupplyRewardEligible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supply_reward_eligible", values[i])
			} else if value.Valid {
				_m.SupplyRewardEligible = value.Bool
			}
		case usagebillingevent.FieldSupplyOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field supply_owner_user_id", values[i])
			} else if value.Valid {
				_m.SupplyOwnerUserID = new(int64)
				*_m.SupplyOwnerUserID = value.Int64
			}
		case usagebillingevent.FieldSupplyRewardMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field supply_reward_multiplier", values[i])
			} else if value.Valid {
				_m.SupplyRewardMultiplier = value.Float64
			}
		case usagebillingevent.FieldSupplyAccountStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supply_account_status", values[i])
			} else if value.Valid {
				_m.SupplyAccountStatus = value.String
			}
		case usagebillingevent.FieldSupplySource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supply_source", values[i])
			} else if value.Valid {
				_m.SupplySource = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageBillingEvent.
// This includes values selected through modifiers, order, etc.
func (_m *UsageBillingEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UsageBillingEvent.
// Note that you need to call UsageBillingEvent.Unwrap() before calling this method if this UsageBillingEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageBillingEvent) Update() *UsageBillingEventUpdateOne {
	return NewUsageBillingEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageBillingEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageBillingEvent) Unwrap() *UsageBillingEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageBillingEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageBillingEvent) String() string {
	var builder strings.Builder
	builder.WriteString("UsageBillingEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=")
	builder.WriteString(_m.RequestFingerprint)
	builder.WriteString(", ")
	if v := _m.RequestPayloadHash; v != nil {
		builder.WriteString("request_payload_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.AccountType; v != nil {
		builder.WriteString("account_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("service_tier=")
	builder.WriteString(_m.ServiceTier)
	builder.WriteString(", ")
	builder.WriteString("reasoning_effort=")
	builder.WriteString(_m.ReasoningEffort)
	builder.WriteString(", ")
	builder.WriteString("billing_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingType))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_5m_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation5mTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_1h_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation1hTokens))
	builder.WriteString(", ")
	builder.WriteString("total_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("balance_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceCost))
	builder.WriteString(", ")
	builder.WriteString("subscription_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionCost))
	builder.WriteString(", ")
	builder.WriteString("api_key_quota_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyQuotaCost))
	builder.WriteString(", ")
	builder.WriteString("api_key_rate_limit_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyRateLimitCost))
	builder.WriteString(", ")
	builder.WriteString("account_quota_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountQuotaCost))
	builder.WriteString(", ")
	builder.WriteString("supply_reward_eligible=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupplyRewardEligible))
	builder.WriteString(", ")
	if v := _m.SupplyOwnerUserID; v != nil {
		builder.WriteString("supply_owner_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("supply_reward_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupplyRewardMultiplier))
	builder.WriteString(", ")
	builder.WriteString("supply_account_status=")
	builder.WriteString(_m.SupplyAccountStatus)
	builder.WriteString(", ")
	builder.WriteString("supply_source=")
	builder.WriteString(_m.SupplySource)
	builder.WriteByte(')')
	return builder.String()
}

// UsageBillingEvents is a parsable slice of UsageBillingEvent.
type UsageBillingEvents []*UsageBillingEvent
