// Code generated by ent, DO NOT EDIT.

package resourcesupplybalance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldUserID, v))
}

// AvailableAmount applies equality check predicate on the "available_amount" field. It's identical to AvailableAmountEQ.
func AvailableAmount(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldAvailableAmount, v))
}

// LifetimeEarnedAmount applies equality check predicate on the "lifetime_earned_amount" field. It's identical to LifetimeEarnedAmountEQ.
func LifetimeEarnedAmount(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldLifetimeEarnedAmount, v))
}

// LifetimeTransferredAmount applies equality check predicate on the "lifetime_transferred_amount" field. It's identical to LifetimeTransferredAmountEQ.
func LifetimeTransferredAmount(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldLifetimeTransferredAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNotIn(FieldUserID, vs...))
}

// AvailableAmountEQ applies the EQ predicate on the "available_amount" field.
func AvailableAmountEQ(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldAvailableAmount, v))
}

// AvailableAmountNEQ applies the NEQ predicate on the "available_amount" field.
func AvailableAmountNEQ(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNEQ(FieldAvailableAmount, v))
}

// AvailableAmountIn applies the In predicate on the "available_amount" field.
func AvailableAmountIn(vs ...float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldIn(FieldAvailableAmount, vs...))
}

// AvailableAmountNotIn applies the NotIn predicate on the "available_amount" field.
func AvailableAmountNotIn(vs ...float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNotIn(FieldAvailableAmount, vs...))
}

// AvailableAmountGT applies the GT predicate on the "available_amount" field.
func AvailableAmountGT(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGT(FieldAvailableAmount, v))
}

// AvailableAmountGTE applies the GTE predicate on the "available_amount" field.
func AvailableAmountGTE(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGTE(FieldAvailableAmount, v))
}

// AvailableAmountLT applies the LT predicate on the "available_amount" field.
func AvailableAmountLT(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLT(FieldAvailableAmount, v))
}

// AvailableAmountLTE applies the LTE predicate on the "available_amount" field.
func AvailableAmountLTE(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLTE(FieldAvailableAmount, v))
}

// LifetimeEarnedAmountEQ applies the EQ predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountEQ(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldLifetimeEarnedAmount, v))
}

// LifetimeEarnedAmountNEQ applies the NEQ predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountNEQ(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNEQ(FieldLifetimeEarnedAmount, v))
}

// LifetimeEarnedAmountIn applies the In predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountIn(vs ...float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldIn(FieldLifetimeEarnedAmount, vs...))
}

// LifetimeEarnedAmountNotIn applies the NotIn predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountNotIn(vs ...float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNotIn(FieldLifetimeEarnedAmount, vs...))
}

// LifetimeEarnedAmountGT applies the GT predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountGT(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGT(FieldLifetimeEarnedAmount, v))
}

// LifetimeEarnedAmountGTE applies the GTE predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountGTE(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGTE(FieldLifetimeEarnedAmount, v))
}

// LifetimeEarnedAmountLT applies the LT predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountLT(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLT(FieldLifetimeEarnedAmount, v))
}

// LifetimeEarnedAmountLTE applies the LTE predicate on the "lifetime_earned_amount" field.
func LifetimeEarnedAmountLTE(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLTE(FieldLifetimeEarnedAmount, v))
}

// LifetimeTransferredAmountEQ applies the EQ predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountEQ(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldEQ(FieldLifetimeTransferredAmount, v))
}

// LifetimeTransferredAmountNEQ applies the NEQ predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountNEQ(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNEQ(FieldLifetimeTransferredAmount, v))
}

// LifetimeTransferredAmountIn applies the In predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountIn(vs ...float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldIn(FieldLifetimeTransferredAmount, vs...))
}

// LifetimeTransferredAmountNotIn applies the NotIn predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountNotIn(vs ...float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldNotIn(FieldLifetimeTransferredAmount, vs...))
}

// LifetimeTransferredAmountGT applies the GT predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountGT(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGT(FieldLifetimeTransferredAmount, v))
}

// LifetimeTransferredAmountGTE applies the GTE predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountGTE(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldGTE(FieldLifetimeTransferredAmount, v))
}

// LifetimeTransferredAmountLT applies the LT predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountLT(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLT(FieldLifetimeTransferredAmount, v))
}

// LifetimeTransferredAmountLTE applies the LTE predicate on the "lifetime_transferred_amount" field.
func LifetimeTransferredAmountLTE(v float64) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.FieldLTE(FieldLifetimeTransferredAmount, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResourceSupplyBalance) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResourceSupplyBalance) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResourceSupplyBalance) predicate.ResourceSupplyBalance {
	return predicate.ResourceSupplyBalance(sql.NotPredicates(p))
}
