// Code generated by ent, DO NOT EDIT.

package ccgoagentcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldWorkspaceID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldUserID, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldTokenHash, v))
}

// NonceHash applies equality check predicate on the "nonce_hash" field. It's identical to NonceHashEQ.
func NonceHash(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldNonceHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldExpiresAt, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldUsedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldRevokedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldWorkspaceID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldUserID, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldContainsFold(FieldTokenHash, v))
}

// NonceHashEQ applies the EQ predicate on the "nonce_hash" field.
func NonceHashEQ(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldNonceHash, v))
}

// NonceHashNEQ applies the NEQ predicate on the "nonce_hash" field.
func NonceHashNEQ(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldNonceHash, v))
}

// NonceHashIn applies the In predicate on the "nonce_hash" field.
func NonceHashIn(vs ...string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldNonceHash, vs...))
}

// NonceHashNotIn applies the NotIn predicate on the "nonce_hash" field.
func NonceHashNotIn(vs ...string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldNonceHash, vs...))
}

// NonceHashGT applies the GT predicate on the "nonce_hash" field.
func NonceHashGT(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldNonceHash, v))
}

// NonceHashGTE applies the GTE predicate on the "nonce_hash" field.
func NonceHashGTE(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldNonceHash, v))
}

// NonceHashLT applies the LT predicate on the "nonce_hash" field.
func NonceHashLT(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldNonceHash, v))
}

// NonceHashLTE applies the LTE predicate on the "nonce_hash" field.
func NonceHashLTE(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldNonceHash, v))
}

// NonceHashContains applies the Contains predicate on the "nonce_hash" field.
func NonceHashContains(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldContains(FieldNonceHash, v))
}

// NonceHashHasPrefix applies the HasPrefix predicate on the "nonce_hash" field.
func NonceHashHasPrefix(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldHasPrefix(FieldNonceHash, v))
}

// NonceHashHasSuffix applies the HasSuffix predicate on the "nonce_hash" field.
func NonceHashHasSuffix(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldHasSuffix(FieldNonceHash, v))
}

// NonceHashEqualFold applies the EqualFold predicate on the "nonce_hash" field.
func NonceHashEqualFold(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEqualFold(FieldNonceHash, v))
}

// NonceHashContainsFold applies the ContainsFold predicate on the "nonce_hash" field.
func NonceHashContainsFold(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldContainsFold(FieldNonceHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldExpiresAt, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotNull(FieldUsedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotNull(FieldRevokedAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CcgoAgentCredential) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CcgoAgentCredential) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CcgoAgentCredential) predicate.CcgoAgentCredential {
	return predicate.CcgoAgentCredential(sql.NotPredicates(p))
}
