// Code generated by ent, DO NOT EDIT.

package ccgodevicelogin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeviceCodeHash applies equality check predicate on the "device_code_hash" field. It's identical to DeviceCodeHashEQ.
func DeviceCodeHash(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldDeviceCodeHash, v))
}

// UserCodeHash applies equality check predicate on the "user_code_hash" field. It's identical to UserCodeHashEQ.
func UserCodeHash(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldUserCodeHash, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldUserID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldDeviceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldExpiresAt, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldApprovedAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeviceCodeHashEQ applies the EQ predicate on the "device_code_hash" field.
func DeviceCodeHashEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldDeviceCodeHash, v))
}

// DeviceCodeHashNEQ applies the NEQ predicate on the "device_code_hash" field.
func DeviceCodeHashNEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldDeviceCodeHash, v))
}

// DeviceCodeHashIn applies the In predicate on the "device_code_hash" field.
func DeviceCodeHashIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldDeviceCodeHash, vs...))
}

// DeviceCodeHashNotIn applies the NotIn predicate on the "device_code_hash" field.
func DeviceCodeHashNotIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldDeviceCodeHash, vs...))
}

// DeviceCodeHashGT applies the GT predicate on the "device_code_hash" field.
func DeviceCodeHashGT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldDeviceCodeHash, v))
}

// DeviceCodeHashGTE applies the GTE predicate on the "device_code_hash" field.
func DeviceCodeHashGTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldDeviceCodeHash, v))
}

// DeviceCodeHashLT applies the LT predicate on the "device_code_hash" field.
func DeviceCodeHashLT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldDeviceCodeHash, v))
}

// DeviceCodeHashLTE applies the LTE predicate on the "device_code_hash" field.
func DeviceCodeHashLTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldDeviceCodeHash, v))
}

// DeviceCodeHashContains applies the Contains predicate on the "device_code_hash" field.
func DeviceCodeHashContains(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContains(FieldDeviceCodeHash, v))
}

// DeviceCodeHashHasPrefix applies the HasPrefix predicate on the "device_code_hash" field.
func DeviceCodeHashHasPrefix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasPrefix(FieldDeviceCodeHash, v))
}

// DeviceCodeHashHasSuffix applies the HasSuffix predicate on the "device_code_hash" field.
func DeviceCodeHashHasSuffix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasSuffix(FieldDeviceCodeHash, v))
}

// DeviceCodeHashEqualFold applies the EqualFold predicate on the "device_code_hash" field.
func DeviceCodeHashEqualFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEqualFold(FieldDeviceCodeHash, v))
}

// DeviceCodeHashContainsFold applies the ContainsFold predicate on the "device_code_hash" field.
func DeviceCodeHashContainsFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContainsFold(FieldDeviceCodeHash, v))
}

// UserCodeHashEQ applies the EQ predicate on the "user_code_hash" field.
func UserCodeHashEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldUserCodeHash, v))
}

// UserCodeHashNEQ applies the NEQ predicate on the "user_code_hash" field.
func UserCodeHashNEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldUserCodeHash, v))
}

// UserCodeHashIn applies the In predicate on the "user_code_hash" field.
func UserCodeHashIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldUserCodeHash, vs...))
}

// UserCodeHashNotIn applies the NotIn predicate on the "user_code_hash" field.
func UserCodeHashNotIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldUserCodeHash, vs...))
}

// UserCodeHashGT applies the GT predicate on the "user_code_hash" field.
func UserCodeHashGT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldUserCodeHash, v))
}

// UserCodeHashGTE applies the GTE predicate on the "user_code_hash" field.
func UserCodeHashGTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldUserCodeHash, v))
}

// UserCodeHashLT applies the LT predicate on the "user_code_hash" field.
func UserCodeHashLT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldUserCodeHash, v))
}

// UserCodeHashLTE applies the LTE predicate on the "user_code_hash" field.
func UserCodeHashLTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldUserCodeHash, v))
}

// UserCodeHashContains applies the Contains predicate on the "user_code_hash" field.
func UserCodeHashContains(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContains(FieldUserCodeHash, v))
}

// UserCodeHashHasPrefix applies the HasPrefix predicate on the "user_code_hash" field.
func UserCodeHashHasPrefix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasPrefix(FieldUserCodeHash, v))
}

// UserCodeHashHasSuffix applies the HasSuffix predicate on the "user_code_hash" field.
func UserCodeHashHasSuffix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasSuffix(FieldUserCodeHash, v))
}

// UserCodeHashEqualFold applies the EqualFold predicate on the "user_code_hash" field.
func UserCodeHashEqualFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEqualFold(FieldUserCodeHash, v))
}

// UserCodeHashContainsFold applies the ContainsFold predicate on the "user_code_hash" field.
func UserCodeHashContainsFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContainsFold(FieldUserCodeHash, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotNull(FieldUserID))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContainsFold(FieldDeviceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldExpiresAt, v))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotNull(FieldApprovedAt))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.FieldNotNull(FieldConsumedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CcgoDeviceLogin) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CcgoDeviceLogin) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CcgoDeviceLogin) predicate.CcgoDeviceLogin {
	return predicate.CcgoDeviceLogin(sql.NotPredicates(p))
}
